--
-- PostgreSQL database dump
--

\restrict JrckLJ3PICEBfhwwjUjQY9PBDpkMZtnbep5Puv8j4NK96TwefVXaywgDFzs6J16

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achat_journalier; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.achat_journalier (
    id bigint NOT NULL,
    cloture boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_achat date NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    fournisseur_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.achat_journalier OWNER TO fishcam_user;

--
-- Name: achat_journalier_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.achat_journalier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achat_journalier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    active boolean NOT NULL,
    avatar_path character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    role character varying(255) NOT NULL,
    scope character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    default_poissonnerie_id bigint,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'PATRON'::character varying, 'CAISSIERE'::character varying, 'ENREGISTREUR'::character varying])::text[]))),
    CONSTRAINT app_user_scope_check CHECK (((scope)::text = ANY ((ARRAY['MULTI_POISSONNERIE'::character varying, 'SINGLE_POISSONNERIE'::character varying])::text[])))
);


ALTER TABLE public.app_user OWNER TO fishcam_user;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    details character varying(1000),
    entity_id bigint,
    entity_name character varying(255) NOT NULL,
    performed_by character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone
);


ALTER TABLE public.audit_logs OWNER TO fishcam_user;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: backup_record; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.backup_record (
    id bigint NOT NULL,
    date_execution timestamp(6) without time zone NOT NULL,
    success boolean NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT backup_record_type_check CHECK (((type)::text = ANY ((ARRAY['HEBDOMADAIRE'::character varying, 'MENSUEL'::character varying])::text[])))
);


ALTER TABLE public.backup_record OWNER TO fishcam_user;

--
-- Name: backup_record_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.backup_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backup_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bilan_mensuel; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.bilan_mensuel (
    id bigint NOT NULL,
    annee integer NOT NULL,
    benefice_meilleur_jour numeric(38,2) NOT NULL,
    benefice_net_mois numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    meilleur_jour_benefice date NOT NULL,
    mois integer NOT NULL,
    montant_dettes_mois numeric(38,2) NOT NULL,
    nombre_jours_travailles integer NOT NULL,
    total_achat_mois numeric(38,2) NOT NULL,
    total_depenses_mois numeric(38,2) NOT NULL,
    total_vente_previsible_mois numeric(38,2) NOT NULL,
    total_vente_realisee numeric(38,2) NOT NULL,
    user_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.bilan_mensuel OWNER TO fishcam_user;

--
-- Name: bilan_mensuel_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.bilan_mensuel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bilan_mensuel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    active boolean,
    address character varying(255),
    cni character varying(50),
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth date,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    notes character varying(1000),
    phone character varying(20) NOT NULL,
    quartier character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    create_by_id bigint,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.client OWNER TO fishcam_user;

--
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cloture_journaliere; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.cloture_journaliere (
    id bigint NOT NULL,
    argent_caisse numeric(38,2) NOT NULL,
    autres_frais numeric(38,2) NOT NULL,
    benefice_net numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    description_autres character varying(500),
    fond_de_caisse numeric(38,2) NOT NULL,
    montant_dettes_jour numeric(38,2) NOT NULL,
    montant_rembourse_jour numeric(38,2) NOT NULL,
    nombre_dettes_jour integer NOT NULL,
    ration numeric(38,2) NOT NULL,
    total_achat numeric(38,2) NOT NULL,
    total_depenses numeric(38,2) NOT NULL,
    total_vente_previsible numeric(38,2) NOT NULL,
    transport numeric(38,2) NOT NULL,
    vente_realisee numeric(38,2) NOT NULL,
    cloture_par_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.cloture_journaliere OWNER TO fishcam_user;

--
-- Name: cloture_journaliere_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.cloture_journaliere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cloture_journaliere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compte_courant; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.compte_courant (
    id bigint NOT NULL,
    date_ouverture timestamp(6) without time zone NOT NULL,
    limite_credit_max numeric(10,2) NOT NULL,
    solde numeric(10,2) NOT NULL,
    statut character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id bigint,
    CONSTRAINT compte_courant_statut_check CHECK (((statut)::text = ANY ((ARRAY['ACTIF'::character varying, 'SUSPENDU'::character varying, 'BLOQUE'::character varying])::text[])))
);


ALTER TABLE public.compte_courant OWNER TO fishcam_user;

--
-- Name: compte_courant_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.compte_courant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compte_courant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employe; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.employe (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(50) NOT NULL,
    poste character varying(50) NOT NULL,
    prenom character varying(50) NOT NULL,
    salaire numeric(38,2) NOT NULL,
    telephone character varying(20),
    updated_at timestamp(6) without time zone NOT NULL,
    poissonnerie_id bigint NOT NULL,
    user_id bigint
);


ALTER TABLE public.employe OWNER TO fishcam_user;

--
-- Name: employe_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.employe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: epargne_saving; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.epargne_saving (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_balance numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id bigint
);


ALTER TABLE public.epargne_saving OWNER TO fishcam_user;

--
-- Name: epargne_saving_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.epargne_saving ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.epargne_saving_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_livreur; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.evaluation_livreur (
    id bigint NOT NULL,
    commentaire character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    date_evaluation date NOT NULL,
    probleme_signale boolean NOT NULL,
    qualite_produit integer NOT NULL,
    respect_poids integer NOT NULL,
    achat_journalier_id bigint NOT NULL,
    livreur_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.evaluation_livreur OWNER TO fishcam_user;

--
-- Name: evaluation_livreur_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.evaluation_livreur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_livreur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fournisseur; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.fournisseur (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(255) NOT NULL,
    telephone character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    ville character varying(100)
);


ALTER TABLE public.fournisseur OWNER TO fishcam_user;

--
-- Name: fournisseur_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.fournisseur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fournisseur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ligne_achat; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.ligne_achat (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    montant_carton numeric(38,2) NOT NULL,
    poids_kg numeric(38,2) NOT NULL,
    prix_unitaire_carton numeric(38,2) NOT NULL,
    prix_vente_kilo numeric(38,2) NOT NULL,
    quantite_cartons integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    achat_journalier_id bigint NOT NULL,
    produit_id bigint NOT NULL
);


ALTER TABLE public.ligne_achat OWNER TO fishcam_user;

--
-- Name: ligne_achat_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.ligne_achat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ligne_achat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livreur; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.livreur (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(255) NOT NULL,
    prenom character varying(255) NOT NULL,
    telephone character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    fournisseur_id bigint NOT NULL
);


ALTER TABLE public.livreur OWNER TO fishcam_user;

--
-- Name: livreur_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.livreur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livreur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(2500) NOT NULL,
    read boolean NOT NULL,
    type character varying(255) NOT NULL,
    poissonnerie_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['COMPTE_COURANT_ALERTE'::character varying, 'COMPTE_SOLDE'::character varying, 'RAPPORT_JOURNALIER'::character varying, 'INFO'::character varying])::text[])))
);


ALTER TABLE public.notification OWNER TO fishcam_user;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poissonnerie; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.poissonnerie (
    id bigint NOT NULL,
    active boolean NOT NULL,
    address character varying(225),
    created_at timestamp(6) without time zone NOT NULL,
    fond_de_caisse_defaut numeric(38,2) NOT NULL,
    loyer numeric(38,2) NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20),
    pret_actif boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.poissonnerie OWNER TO fishcam_user;

--
-- Name: poissonnerie_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.poissonnerie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.poissonnerie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produit; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.produit (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(100) NOT NULL,
    poids_par_carton numeric(38,2) NOT NULL,
    unite character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT produit_unite_check CHECK (((unite)::text = 'KG'::text))
);


ALTER TABLE public.produit OWNER TO fishcam_user;

--
-- Name: produit_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.produit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rapport_journalier_record; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.rapport_journalier_record (
    id bigint NOT NULL,
    date_rapport date NOT NULL,
    generated_at timestamp(6) without time zone,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.rapport_journalier_record OWNER TO fishcam_user;

--
-- Name: rapport_journalier_record_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.rapport_journalier_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rapport_journalier_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_compte_courant; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.transaction_compte_courant (
    id bigint NOT NULL,
    description character varying(500),
    montant numeric(10,2) NOT NULL,
    notes character varying(1000),
    solde_apres numeric(10,2) NOT NULL,
    solde_precedent numeric(10,2) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    compte_courant_id bigint NOT NULL,
    effectue_par_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL,
    CONSTRAINT transaction_compte_courant_type_check CHECK (((type)::text = ANY ((ARRAY['EMPRUNT'::character varying, 'REMBOURSEMENT'::character varying])::text[])))
);


ALTER TABLE public.transaction_compte_courant OWNER TO fishcam_user;

--
-- Name: transaction_compte_courant_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.transaction_compte_courant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_compte_courant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_saving; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.transaction_saving (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    effectue_par_id bigint,
    saving_id bigint NOT NULL,
    poissonnerie_id bigint,
    CONSTRAINT transaction_saving_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOT'::character varying, 'RETRAIT'::character varying])::text[])))
);


ALTER TABLE public.transaction_saving OWNER TO fishcam_user;

--
-- Name: transaction_saving_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.transaction_saving ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_saving_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: achat_journalier; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.achat_journalier (id, cloture, created_at, date_achat, updated_at, user_id, fournisseur_id, poissonnerie_id) FROM stdin;
\.


--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.app_user (id, active, avatar_path, created_at, first_name, last_name, password, phone, role, scope, updated_at, default_poissonnerie_id) FROM stdin;
1	t	\N	2026-04-11 23:47:32.942123	Super	Admin	$2a$10$4TM5pSr24ZDauUDPFhn3pOKgCOK5sfS1zDeNYfnbIUW0j/il9xLE2	692087724	SUPER_ADMIN	MULTI_POISSONNERIE	2026-04-11 23:47:32.942185	1
2	t	\N	2026-04-11 23:47:33.390955	Theophile	FOSSO	$2a$10$6ctRA1bvHL8H3YHcKZm1kuUelYMVhsIZDsnyzSxu8th6qRUgjlNr2	676028800	PATRON	SINGLE_POISSONNERIE	2026-04-11 23:47:33.39105	1
3	t	\N	2026-04-11 23:47:33.883968	Alerte	DJOKO	$2a$10$wvxZalXaepCpCuplfshozuWDl8bJYHYzTeZrYIIV/SAuI3Gwow2Jq	690950871	CAISSIERE	SINGLE_POISSONNERIE	2026-04-11 23:47:33.884069	1
4	t	\N	2026-04-11 23:47:34.324184	Christine	Inconnu	$2a$10$ZvIGP6t19djWYoTqdlGmOuNoI4DX3Xx0OruG8lNxwv7ROiHdzJ8hO	655032752	ENREGISTREUR	SINGLE_POISSONNERIE	2026-04-11 23:47:34.324242	1
\.


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.audit_logs (id, action, details, entity_id, entity_name, performed_by, "timestamp") FROM stdin;
1	REMBOURSEMENT	Action executed via method: enregistrerRemboursement	1	CompteCourant	676028800	2026-05-31 06:08:52.068864
2	EMPRUNT	Action executed via method: enregistrerEmprunt	2	CompteCourant	676028800	2026-05-31 06:14:34.551897
3	CREATE	Action executed via method: createClient	11	Client	655032752	2026-06-03 06:42:00.157891
4	CREATE	Action executed via method: createClient	12	Client	655032752	2026-06-03 06:42:00.15766
5	CREATE	Action executed via method: createClient	13	Client	655032752	2026-06-03 07:03:15.70764
6	CREATE	Action executed via method: createClient	14	Client	655032752	2026-06-03 07:03:53.752644
7	EMPRUNT	Action executed via method: enregistrerEmprunt	1	CompteCourant	676028800	2026-06-05 05:56:26.475723
8	REMBOURSEMENT	Action executed via method: enregistrerRemboursement	1	CompteCourant	676028800	2026-06-05 05:57:03.609887
9	EMPRUNT	Action executed via method: enregistrerEmprunt	1	CompteCourant	676028800	2026-06-05 05:57:41.327975
10	DEPOT	Action executed via method: deposer	2	Epargne	690950871	2026-06-05 07:39:57.32461
11	RETRAIT	Action executed via method: retirer	2	Epargne	690950871	2026-06-05 07:40:02.960914
12	EMPRUNT	Action executed via method: enregistrerEmprunt	1	CompteCourant	690950871	2026-06-05 07:40:46.867468
13	CREATE	Action executed via method: createCompteCourant	11	CompteCourant	690950871	2026-06-05 08:11:50.87993
14	CREATE	Action executed via method: createCompteCourant	12	CompteCourant	690950871	2026-06-05 08:12:44.800877
15	CREATE	Action executed via method: createCompteCourant	13	CompteCourant	690950871	2026-06-05 08:56:14.291358
16	EMPRUNT	Action executed via method: enregistrerEmprunt	13	CompteCourant	690950871	2026-06-05 08:56:20.847243
\.


--
-- Data for Name: backup_record; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.backup_record (id, date_execution, success, type) FROM stdin;
1	2026-04-11 23:48:08.239211	t	HEBDOMADAIRE
2	2026-04-27 15:25:05.463221	t	HEBDOMADAIRE
\.


--
-- Data for Name: bilan_mensuel; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.bilan_mensuel (id, annee, benefice_meilleur_jour, benefice_net_mois, created_at, meilleur_jour_benefice, mois, montant_dettes_mois, nombre_jours_travailles, total_achat_mois, total_depenses_mois, total_vente_previsible_mois, total_vente_realisee, user_id, poissonnerie_id) FROM stdin;
\.


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.client (id, active, address, cni, created_at, date_of_birth, first_name, last_name, notes, phone, quartier, updated_at, create_by_id, poissonnerie_id) FROM stdin;
1	t	Derrière le marché	123456789	2026-05-14 23:30:53.038464	\N	Maman	Clementine	\N	690000011	Akwa	2026-05-14 23:30:53.038464	1	1
2	t	Carrefour	987654321	2026-05-14 23:30:53.038464	\N	Papa	Simon	\N	690000012	Deido	2026-05-14 23:30:53.038464	1	1
3	t	Avenue principale	456123789	2026-05-14 23:30:53.038464	\N	Tante	Marie	\N	690000013	Bonamoussadi	2026-05-14 23:30:53.038464	1	2
11	t	Logpom	123456789	2026-06-03 06:42:00.114654	2004-07-05	Arsene Christophe	NGUEDAM MOUATCHO	\N	692087724	carrefour Doctat	2026-06-03 06:42:00.11469	4	1
12	t	Logpom	123456789	2026-06-03 06:42:00.109353	2004-07-05	Arsene Christophe	NGUEDAM MOUATCHO	\N	692087724	carrefour Doctat	2026-06-03 06:42:00.109393	4	1
13	t	Logpom	123456	2026-06-03 07:03:15.662488	2026-04-08	Arsene Christophe	NGUEDAM MOUATCHO	\N	692087723	ff	2026-06-03 07:03:15.66252	4	1
14	t	Logpom	123456	2026-06-03 07:03:53.745101	2026-04-08	Arsene Christophe	NGUEDAM MOUATCHO	\N	692087722	ff	2026-06-03 07:03:53.745134	4	1
\.


--
-- Data for Name: cloture_journaliere; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.cloture_journaliere (id, argent_caisse, autres_frais, benefice_net, created_at, date, description_autres, fond_de_caisse, montant_dettes_jour, montant_rembourse_jour, nombre_dettes_jour, ration, total_achat, total_depenses, total_vente_previsible, transport, vente_realisee, cloture_par_id, poissonnerie_id) FROM stdin;
\.


--
-- Data for Name: compte_courant; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.compte_courant (id, date_ouverture, limite_credit_max, solde, statut, updated_at, client_id, created_by_id) FROM stdin;
3	2026-05-14 23:30:53.049993	50000.00	-55000.00	BLOQUE	2026-05-14 23:30:53.049993	3	1
2	2026-05-14 23:30:53.049993	20000.00	-6000.00	ACTIF	2026-05-31 06:14:34.554417	2	1
1	2026-05-14 23:30:53.049993	50000.00	-13499.00	ACTIF	2026-06-05 07:40:46.869229	1	1
11	2026-06-05 08:11:50.871742	50000.00	0.00	ACTIF	2026-06-05 08:11:50.871756	12	3
12	2026-06-05 08:12:44.798404	50000.00	0.00	ACTIF	2026-06-05 08:12:44.798419	13	3
13	2026-06-05 08:56:14.260927	50000.00	-5000.00	ACTIF	2026-06-05 08:56:20.852957	14	3
\.


--
-- Data for Name: employe; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.employe (id, actif, created_at, nom, poste, prenom, salaire, telephone, updated_at, poissonnerie_id, user_id) FROM stdin;
\.


--
-- Data for Name: epargne_saving; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.epargne_saving (id, created_at, current_balance, updated_at, client_id, created_by_id) FROM stdin;
1	2026-05-14 23:30:53.056876	25000.00	2026-05-14 23:30:53.056876	1	1
3	2026-05-14 23:30:53.056876	0.00	2026-05-14 23:30:53.056876	3	1
2	2026-05-14 23:30:53.056876	100000.00	2026-06-05 07:40:02.965113	2	1
\.


--
-- Data for Name: evaluation_livreur; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.evaluation_livreur (id, commentaire, created_at, date_evaluation, probleme_signale, qualite_produit, respect_poids, achat_journalier_id, livreur_id, user_id) FROM stdin;
\.


--
-- Data for Name: fournisseur; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.fournisseur (id, actif, created_at, nom, telephone, updated_at, ville) FROM stdin;
1	t	2026-04-11 23:47:34.35493	CONGELCAM	\N	2026-04-11 23:47:34.354995	Nkongsamba
2	t	2026-05-14 23:12:13.209835	QUEEN FISH	690000000	2026-05-14 23:12:13.209835	Yaoundé
\.


--
-- Data for Name: ligne_achat; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.ligne_achat (id, created_at, montant_carton, poids_kg, prix_unitaire_carton, prix_vente_kilo, quantite_cartons, updated_at, achat_journalier_id, produit_id) FROM stdin;
\.


--
-- Data for Name: livreur; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.livreur (id, actif, created_at, nom, prenom, telephone, updated_at, fournisseur_id) FROM stdin;
1	t	2026-05-14 23:30:53.063537	Ndjana	Paul	671000001	2026-05-14 23:30:53.063537	1
2	t	2026-05-14 23:30:53.063537	Talla	Serge	671000002	2026-05-14 23:30:53.063537	2
\.


--
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.notification (id, created_at, message, read, type, poissonnerie_id, user_id) FROM stdin;
1	2026-04-11 23:47:34.548921	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-10 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
2	2026-04-11 23:47:34.57502	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-10 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
3	2026-04-11 23:47:34.600334	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-10 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
4	2026-04-11 23:47:34.628148	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-10 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
5	2026-04-11 23:47:34.682475	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-09 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
6	2026-04-11 23:47:34.70921	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-09 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
7	2026-04-11 23:47:34.768745	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-09 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
8	2026-04-11 23:47:34.789233	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-09 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
9	2026-04-11 23:47:34.85095	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-08 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
10	2026-04-11 23:47:34.89221	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-08 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
11	2026-04-11 23:47:34.928401	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-08 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
12	2026-04-11 23:47:34.95083	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-08 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
13	2026-04-11 23:47:35.002165	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-07 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
14	2026-04-11 23:47:35.02768	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-07 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
15	2026-04-11 23:47:35.048343	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-07 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
16	2026-04-11 23:47:35.070516	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-07 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
17	2026-04-11 23:47:35.115668	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-06 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
18	2026-04-11 23:47:35.138343	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-06 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
19	2026-04-11 23:47:35.159063	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-06 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
20	2026-04-11 23:47:35.177412	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-06 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
21	2026-04-11 23:47:35.211237	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-05 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
22	2026-04-11 23:47:35.227649	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-05 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
23	2026-04-11 23:47:35.249437	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-05 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
24	2026-04-11 23:47:35.269094	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-05 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
25	2026-04-11 23:47:35.31665	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-04 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
26	2026-04-11 23:47:35.340266	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-04 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
27	2026-04-11 23:47:35.360951	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-04 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
28	2026-04-11 23:47:35.385321	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-04 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
29	2026-04-24 15:25:10.326408	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-23 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
30	2026-04-24 15:25:10.421348	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-23 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
31	2026-04-24 15:25:10.444422	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-23 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
32	2026-04-24 15:25:10.467603	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-23 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
33	2026-04-24 15:25:10.528636	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-22 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
34	2026-04-24 15:25:10.570486	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-22 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
35	2026-04-24 15:25:10.604171	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-22 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
36	2026-04-24 15:25:10.630593	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-22 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
37	2026-04-24 15:25:10.690635	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-21 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
38	2026-04-24 15:25:10.716459	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-21 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
39	2026-04-24 15:25:10.738659	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-21 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
40	2026-04-24 15:25:10.764459	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-21 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
41	2026-04-24 15:25:10.831455	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-20 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
42	2026-04-24 15:25:10.88518	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-20 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
43	2026-04-24 15:25:10.937353	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-20 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
44	2026-04-24 15:25:10.964638	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-20 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
45	2026-04-24 15:25:11.054793	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-19 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
46	2026-04-24 15:25:11.085745	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-19 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
47	2026-04-24 15:25:11.105903	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-19 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
48	2026-04-24 15:25:11.128753	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-19 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
49	2026-04-24 15:25:11.177383	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-18 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
50	2026-04-24 15:25:11.197691	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-18 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
51	2026-04-24 15:25:11.230611	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-18 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
52	2026-04-24 15:25:11.262527	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-18 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
53	2026-04-24 15:25:11.308734	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-17 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
54	2026-04-24 15:25:11.334845	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-17 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
55	2026-04-24 15:25:11.357991	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-17 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
56	2026-04-24 15:25:11.37942	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-17 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
57	2026-04-27 15:25:05.659919	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-26 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
58	2026-04-27 15:25:05.689344	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-26 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
59	2026-04-27 15:25:05.715366	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-26 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
60	2026-04-27 15:25:05.739174	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-26 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
61	2026-04-27 15:25:05.792015	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-25 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
62	2026-04-27 15:25:05.818383	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-25 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
63	2026-04-27 15:25:05.850694	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-25 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
64	2026-04-27 15:25:05.881743	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-25 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
65	2026-04-27 15:25:05.935109	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-24 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
66	2026-04-27 15:25:05.962424	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-24 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
67	2026-04-27 15:25:05.988347	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-24 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
68	2026-04-27 15:25:06.019212	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-04-24 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
69	2026-05-14 11:36:07.449316	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-13 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
70	2026-05-14 11:36:07.648105	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-13 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
71	2026-05-14 11:36:07.776974	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-13 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
72	2026-05-14 11:36:07.848281	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-13 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
73	2026-05-14 11:36:07.948885	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-12 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
74	2026-05-14 11:36:08.057096	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-12 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
75	2026-05-14 11:36:08.100386	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-12 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
76	2026-05-14 11:36:08.17662	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-12 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
77	2026-05-14 11:36:08.372116	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-11 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
78	2026-05-14 11:36:08.402828	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-11 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
79	2026-05-14 11:36:08.435199	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-11 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
80	2026-05-14 11:36:08.464479	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-11 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
81	2026-05-14 11:36:08.627231	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-10 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
82	2026-05-14 11:36:08.694281	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-10 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
83	2026-05-14 11:36:08.762368	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-10 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
84	2026-05-14 11:36:08.856499	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-10 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
85	2026-05-14 11:36:08.97752	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-09 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
86	2026-05-14 11:36:09.025087	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-09 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
87	2026-05-14 11:36:09.147266	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-09 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
88	2026-05-14 11:36:09.208246	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-09 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
89	2026-05-14 11:36:09.371906	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-08 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
90	2026-05-14 11:36:09.421238	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-08 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
91	2026-05-14 11:36:09.494991	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-08 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
92	2026-05-14 11:36:09.572563	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-08 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
93	2026-05-14 11:36:09.709588	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-07 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
94	2026-05-14 11:36:09.738879	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-07 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
95	2026-05-14 11:36:09.772857	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-07 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
96	2026-05-14 11:36:09.79681	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-07 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
97	2026-05-14 19:00:00.480553	📊 Rapport du 2026-05-14\n\n💰 Emprunts : 0 transactions - 0 FCFA\n💵 Remboursements : 0 transactions - 0 FCFA\n📉 Solde net : 0 FCFA\n\n⚠️ Comptes en dette : 0 clients\n💳 Total dettes actives : 0 FCFA	f	RAPPORT_JOURNALIER	1	1
98	2026-05-14 19:00:00.51207	📊 Rapport du 2026-05-14\n\n💰 Emprunts : 0 transactions - 0 FCFA\n💵 Remboursements : 0 transactions - 0 FCFA\n📉 Solde net : 0 FCFA\n\n⚠️ Comptes en dette : 0 clients\n💳 Total dettes actives : 0 FCFA	f	RAPPORT_JOURNALIER	1	2
99	2026-05-14 19:00:00.517244	📊 Rapport du 2026-05-14\n\n💰 Emprunts : 0 transactions - 0 FCFA\n💵 Remboursements : 0 transactions - 0 FCFA\n📉 Solde net : 0 FCFA\n\n⚠️ Comptes en dette : 0 clients\n💳 Total dettes actives : 0 FCFA	f	RAPPORT_JOURNALIER	1	3
100	2026-05-14 19:00:00.522917	📊 Rapport du 2026-05-14\n\n💰 Emprunts : 0 transactions - 0 FCFA\n💵 Remboursements : 0 transactions - 0 FCFA\n📉 Solde net : 0 FCFA\n\n⚠️ Comptes en dette : 0 clients\n💳 Total dettes actives : 0 FCFA	f	RAPPORT_JOURNALIER	1	4
101	2026-05-26 18:00:12.729699	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-25 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
102	2026-05-26 18:00:12.834012	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-25 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
103	2026-05-26 18:00:12.862492	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-25 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
104	2026-05-26 18:00:12.891018	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-25 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
105	2026-05-26 18:00:12.954944	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-24 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
106	2026-05-26 18:00:12.984811	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-24 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
107	2026-05-26 18:00:13.012469	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-24 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
108	2026-05-26 18:00:13.04713	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-24 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
109	2026-05-26 18:00:13.123545	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-23 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
110	2026-05-26 18:00:13.147424	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-23 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
111	2026-05-26 18:00:13.176032	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-23 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
112	2026-05-26 18:00:13.201092	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-23 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
113	2026-05-26 18:00:13.281581	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-22 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
114	2026-05-26 18:00:13.320514	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-22 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
115	2026-05-26 18:00:13.351875	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-22 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
116	2026-05-26 18:00:13.384015	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-22 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
117	2026-05-26 18:00:13.447245	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-21 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
118	2026-05-26 18:00:13.483126	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-21 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
119	2026-05-26 18:00:13.522611	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-21 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
120	2026-05-26 18:00:13.582738	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-21 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
121	2026-05-26 18:00:13.646726	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-20 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
122	2026-05-26 18:00:13.692311	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-20 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
123	2026-05-26 18:00:13.761457	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-20 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
124	2026-05-26 18:00:13.817008	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-20 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
125	2026-05-26 18:00:13.93117	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-19 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
126	2026-05-26 18:00:13.977183	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-19 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
127	2026-05-26 18:00:14.005799	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-19 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
128	2026-05-26 18:00:14.036396	⚠️ JOURNÉE NON CLÔTURÉE\n\nLe rapport du 2026-05-19 n'a pas été généré.\nLe PC était peut-être éteint à 19h ce jour-là.\nConsultez les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
129	2026-05-26 19:00:00.171856	📊 Rapport du 2026-05-26\n\n💰 Emprunts : 0 transactions - 0 FCFA\n💵 Remboursements : 0 transactions - 0 FCFA\n📉 Solde net : 0 FCFA\n\n⚠️ Comptes en dette : 1 clients\n💳 Total dettes actives : 15000.00 FCFA	f	RAPPORT_JOURNALIER	1	1
130	2026-05-26 19:00:00.182065	📊 Rapport du 2026-05-26\n\n💰 Emprunts : 0 transactions - 0 FCFA\n💵 Remboursements : 0 transactions - 0 FCFA\n📉 Solde net : 0 FCFA\n\n⚠️ Comptes en dette : 1 clients\n💳 Total dettes actives : 15000.00 FCFA	f	RAPPORT_JOURNALIER	1	2
131	2026-05-26 19:00:00.18943	📊 Rapport du 2026-05-26\n\n💰 Emprunts : 0 transactions - 0 FCFA\n💵 Remboursements : 0 transactions - 0 FCFA\n📉 Solde net : 0 FCFA\n\n⚠️ Comptes en dette : 1 clients\n💳 Total dettes actives : 15000.00 FCFA	f	RAPPORT_JOURNALIER	1	3
132	2026-05-26 19:00:00.196507	📊 Rapport du 2026-05-26\n\n💰 Emprunts : 0 transactions - 0 FCFA\n💵 Remboursements : 0 transactions - 0 FCFA\n📉 Solde net : 0 FCFA\n\n⚠️ Comptes en dette : 1 clients\n💳 Total dettes actives : 15000.00 FCFA	f	RAPPORT_JOURNALIER	1	4
133	2026-05-29 17:07:10.05802	Alerte : journée non clôturée\n\nLe rapport du 2026-05-28 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
134	2026-05-29 17:07:10.158775	Alerte : journée non clôturée\n\nLe rapport du 2026-05-28 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
135	2026-05-29 17:07:10.20893	Alerte : journée non clôturée\n\nLe rapport du 2026-05-28 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
136	2026-05-29 17:07:10.2448	Alerte : journée non clôturée\n\nLe rapport du 2026-05-28 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
137	2026-05-29 17:07:10.337772	Alerte : journée non clôturée\n\nLe rapport du 2026-05-27 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
138	2026-05-29 17:07:10.362864	Alerte : journée non clôturée\n\nLe rapport du 2026-05-27 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
139	2026-05-29 17:07:10.386138	Alerte : journée non clôturée\n\nLe rapport du 2026-05-27 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
140	2026-05-29 17:07:10.408392	Alerte : journée non clôturée\n\nLe rapport du 2026-05-27 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
142	2026-05-29 17:40:12.699883	Compte soldé\\nClient : Test User\\nLe compte courant a été complètement soldé.	t	COMPTE_SOLDE	1	1
143	2026-05-29 17:44:22.576135	Compte soldé\nClient : Test User\nLe compte courant a été complètement soldé.	t	COMPTE_SOLDE	1	1
145	2026-05-29 19:00:00.439848	Rapport du 29 mai 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 1 clients\nTotal dettes actives : 15000 FCFA	f	RAPPORT_JOURNALIER	1	2
146	2026-05-29 19:00:00.44552	Rapport du 29 mai 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 1 clients\nTotal dettes actives : 15000 FCFA	f	RAPPORT_JOURNALIER	1	3
141	2026-05-29 17:40:12.699883	Alerte compte courant : Seuil franchi\\nClient : Test User\\nSeuil : -5000 FCFA\\nSolde actuel : -6000 FCFA	t	COMPTE_COURANT_ALERTE	1	1
147	2026-05-29 19:00:00.452097	Rapport du 29 mai 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 1 clients\nTotal dettes actives : 15000 FCFA	f	RAPPORT_JOURNALIER	1	4
144	2026-05-29 19:00:00.430285	Rapport du 29 mai 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 1 clients\nTotal dettes actives : 15000 FCFA	t	RAPPORT_JOURNALIER	1	1
148	2026-05-31 05:59:46.959185	Alerte : journée non clôturée\n\nLe rapport du 2026-05-30 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
149	2026-05-31 05:59:46.98423	Alerte : journée non clôturée\n\nLe rapport du 2026-05-30 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
150	2026-05-31 05:59:46.992918	Alerte : journée non clôturée\n\nLe rapport du 2026-05-30 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
151	2026-05-31 05:59:47.001978	Alerte : journée non clôturée\n\nLe rapport du 2026-05-30 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
152	2026-05-31 06:08:52.054363	Compte soldé\nClient : Maman Clementine\nLe compte courant a été complètement soldé.	f	COMPTE_SOLDE	1	1
153	2026-05-31 06:08:52.057519	Compte soldé\nClient : Maman Clementine\nLe compte courant a été complètement soldé.	f	COMPTE_SOLDE	1	2
154	2026-05-31 06:14:34.545813	Alerte compte courant : Seuil franchi\nClient : Papa Simon\nSeuil : -5000 FCFA\nSolde actuel : -6000 FCFA	f	COMPTE_COURANT_ALERTE	1	1
155	2026-05-31 06:14:34.548861	Alerte compte courant : Seuil franchi\nClient : Papa Simon\nSeuil : -5000 FCFA\nSolde actuel : -6000 FCFA	f	COMPTE_COURANT_ALERTE	1	2
156	2026-06-02 21:50:09.833653	Alerte : journée non clôturée\n\nLe rapport du 2026-06-01 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
157	2026-06-02 21:50:09.985479	Alerte : journée non clôturée\n\nLe rapport du 2026-06-01 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
158	2026-06-02 21:50:10.019233	Alerte : journée non clôturée\n\nLe rapport du 2026-06-01 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
159	2026-06-02 21:50:10.060052	Alerte : journée non clôturée\n\nLe rapport du 2026-06-01 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
160	2026-06-02 21:50:10.125938	Alerte : journée non clôturée\n\nLe rapport du 2026-05-31 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
161	2026-06-02 21:50:10.163442	Alerte : journée non clôturée\n\nLe rapport du 2026-05-31 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
162	2026-06-02 21:50:10.195657	Alerte : journée non clôturée\n\nLe rapport du 2026-05-31 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
163	2026-06-02 21:50:10.233307	Alerte : journée non clôturée\n\nLe rapport du 2026-05-31 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
164	2026-06-03 18:07:32.827972	Alerte : journée non clôturée\n\nLe rapport du 2026-06-02 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
165	2026-06-03 18:07:32.923782	Alerte : journée non clôturée\n\nLe rapport du 2026-06-02 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
166	2026-06-03 18:07:32.955326	Alerte : journée non clôturée\n\nLe rapport du 2026-06-02 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
167	2026-06-03 18:07:32.979203	Alerte : journée non clôturée\n\nLe rapport du 2026-06-02 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
168	2026-06-03 19:00:02.607523	Rapport du 3 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 1 clients\nTotal dettes actives : 6000 FCFA	f	RAPPORT_JOURNALIER	1	1
169	2026-06-03 19:00:02.614776	Rapport du 3 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 1 clients\nTotal dettes actives : 6000 FCFA	f	RAPPORT_JOURNALIER	1	2
170	2026-06-03 19:00:02.624757	Rapport du 3 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 1 clients\nTotal dettes actives : 6000 FCFA	f	RAPPORT_JOURNALIER	1	3
171	2026-06-03 19:00:02.632385	Rapport du 3 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 1 clients\nTotal dettes actives : 6000 FCFA	f	RAPPORT_JOURNALIER	1	4
172	2026-06-05 05:57:41.321769	Alerte compte courant : Seuil franchi\nClient : Maman Clementine\nSeuil : -5000 FCFA\nSolde actuel : -8499 FCFA	f	COMPTE_COURANT_ALERTE	1	1
173	2026-06-05 05:57:41.32634	Alerte compte courant : Seuil franchi\nClient : Maman Clementine\nSeuil : -5000 FCFA\nSolde actuel : -8499 FCFA	f	COMPTE_COURANT_ALERTE	1	2
174	2026-06-05 07:31:17.62196	Alerte : journée non clôturée\n\nLe rapport du 2026-06-04 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
175	2026-06-05 07:31:17.662392	Alerte : journée non clôturée\n\nLe rapport du 2026-06-04 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
176	2026-06-05 07:31:17.66944	Alerte : journée non clôturée\n\nLe rapport du 2026-06-04 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
177	2026-06-05 07:31:17.67983	Alerte : journée non clôturée\n\nLe rapport du 2026-06-04 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
178	2026-06-05 07:40:46.863339	Alerte compte courant : Augmentation significative\nClient : Maman Clementine\nSolde actuel : -13499.00 FCFA	f	COMPTE_COURANT_ALERTE	1	1
179	2026-06-05 07:40:46.865484	Alerte compte courant : Augmentation significative\nClient : Maman Clementine\nSolde actuel : -13499.00 FCFA	f	COMPTE_COURANT_ALERTE	1	2
\.


--
-- Data for Name: poissonnerie; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.poissonnerie (id, active, address, created_at, fond_de_caisse_defaut, loyer, name, phone, pret_actif, updated_at) FROM stdin;
1	t	La Petite mosquée	2026-04-11 23:47:31.982597	10000.00	0.00	FISH CAM VILLE (TEST)	676028800	t	2026-04-11 23:47:31.982882
2	t	Marché Bonamoussadi	2026-05-14 23:12:13.19819	15000.00	45000.00	Poissonnerie La Référence (Bonamoussadi)	+237690000001	f	2026-05-14 23:12:13.19819
\.


--
-- Data for Name: produit; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.produit (id, actif, created_at, nom, poids_par_carton, unite, updated_at) FROM stdin;
1	t	2026-05-14 23:18:05.663673	Maquereau 20+ (Chinchard)	20.00	KG	2026-05-14 23:18:05.663673
2	t	2026-05-14 23:18:05.663673	Maquereau 25+ (Chinchard)	20.00	KG	2026-05-14 23:18:05.663673
3	t	2026-05-14 23:18:05.663673	Bar (Grand)	15.00	KG	2026-05-14 23:18:05.663673
4	t	2026-05-14 23:18:05.663673	Bar (Moyen)	10.00	KG	2026-05-14 23:18:05.663673
5	t	2026-05-14 23:18:05.663673	Silure (Machoiron)	20.00	KG	2026-05-14 23:18:05.663673
6	t	2026-05-14 23:18:05.663673	Carpe	10.00	KG	2026-05-14 23:18:05.663673
7	t	2026-05-14 23:18:05.663673	Saucisse (Saucisson de mer)	10.00	KG	2026-05-14 23:18:05.663673
\.


--
-- Data for Name: rapport_journalier_record; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.rapport_journalier_record (id, date_rapport, generated_at, poissonnerie_id) FROM stdin;
1	2026-05-14	2026-05-14 19:00:00.539344	1
2	2026-05-26	2026-05-26 19:00:00.205473	1
3	2026-05-26	2026-05-26 19:00:00.277232	2
4	2026-05-29	2026-05-29 19:00:00.46085	1
5	2026-05-29	2026-05-29 19:00:00.541711	2
6	2026-06-03	2026-06-03 19:00:02.643545	1
7	2026-06-03	2026-06-03 19:00:02.707128	2
\.


--
-- Data for Name: transaction_compte_courant; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.transaction_compte_courant (id, description, montant, notes, solde_apres, solde_precedent, transaction_date, type, compte_courant_id, effectue_par_id, poissonnerie_id) FROM stdin;
1	Remboursement cash	15000.00	TEST COMPTE SOLDE	0.00	-15000.00	2026-05-31 06:08:52.013948	REMBOURSEMENT	1	2	1
2	TEST SEUIL -5000	6000.00	\N	-6000.00	0.00	2026-05-31 06:14:34.534833	EMPRUNT	2	2	1
3	f	4999.00	\N	-4999.00	0.00	2026-06-05 05:56:26.041663	EMPRUNT	1	2	1
4	Remboursement cash	500.00		-4499.00	-4999.00	2026-06-05 05:57:03.59925	REMBOURSEMENT	1	2	1
5	acc	4000.00	\N	-8499.00	-4499.00	2026-06-05 05:57:41.277625	EMPRUNT	1	2	1
6	a	5000.00	\N	-13499.00	-8499.00	2026-06-05 07:40:46.848831	EMPRUNT	1	3	1
7	a	5000.00	\N	-5000.00	0.00	2026-06-05 08:56:20.840701	EMPRUNT	13	3	1
\.


--
-- Data for Name: transaction_saving; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.transaction_saving (id, amount, transaction_date, type, effectue_par_id, saving_id, poissonnerie_id) FROM stdin;
1	5000.00	2026-06-05 07:39:57.313195	DEPOT	3	2	1
2	5000.00	2026-06-05 07:40:02.955217	RETRAIT	3	2	1
\.


--
-- Name: achat_journalier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.achat_journalier_id_seq', 1, false);


--
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.app_user_id_seq', 10, true);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 16, true);


--
-- Name: backup_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.backup_record_id_seq', 2, true);


--
-- Name: bilan_mensuel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.bilan_mensuel_id_seq', 1, false);


--
-- Name: client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.client_id_seq', 10, true);


--
-- Name: cloture_journaliere_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.cloture_journaliere_id_seq', 1, false);


--
-- Name: compte_courant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.compte_courant_id_seq', 10, true);


--
-- Name: employe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.employe_id_seq', 1, false);


--
-- Name: epargne_saving_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.epargne_saving_id_seq', 10, true);


--
-- Name: evaluation_livreur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.evaluation_livreur_id_seq', 1, false);


--
-- Name: fournisseur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.fournisseur_id_seq', 10, true);


--
-- Name: ligne_achat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.ligne_achat_id_seq', 1, false);


--
-- Name: livreur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.livreur_id_seq', 10, true);


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.notification_id_seq', 179, true);


--
-- Name: poissonnerie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.poissonnerie_id_seq', 10, true);


--
-- Name: produit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.produit_id_seq', 10, true);


--
-- Name: rapport_journalier_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.rapport_journalier_record_id_seq', 7, true);


--
-- Name: transaction_compte_courant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.transaction_compte_courant_id_seq', 7, true);


--
-- Name: transaction_saving_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.transaction_saving_id_seq', 2, true);


--
-- Name: achat_journalier achat_journalier_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT achat_journalier_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: backup_record backup_record_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_pkey PRIMARY KEY (id);


--
-- Name: bilan_mensuel bilan_mensuel_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT bilan_mensuel_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: cloture_journaliere cloture_journaliere_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT cloture_journaliere_pkey PRIMARY KEY (id);


--
-- Name: compte_courant compte_courant_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT compte_courant_pkey PRIMARY KEY (id);


--
-- Name: employe employe_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT employe_pkey PRIMARY KEY (id);


--
-- Name: epargne_saving epargne_saving_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT epargne_saving_pkey PRIMARY KEY (id);


--
-- Name: evaluation_livreur evaluation_livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT evaluation_livreur_pkey PRIMARY KEY (id);


--
-- Name: fournisseur fournisseur_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.fournisseur
    ADD CONSTRAINT fournisseur_pkey PRIMARY KEY (id);


--
-- Name: ligne_achat ligne_achat_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT ligne_achat_pkey PRIMARY KEY (id);


--
-- Name: livreur livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.livreur
    ADD CONSTRAINT livreur_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: poissonnerie poissonnerie_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.poissonnerie
    ADD CONSTRAINT poissonnerie_pkey PRIMARY KEY (id);


--
-- Name: produit produit_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT produit_pkey PRIMARY KEY (id);


--
-- Name: rapport_journalier_record rapport_journalier_record_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT rapport_journalier_record_pkey PRIMARY KEY (id);


--
-- Name: transaction_compte_courant transaction_compte_courant_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT transaction_compte_courant_pkey PRIMARY KEY (id);


--
-- Name: transaction_saving transaction_saving_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT transaction_saving_pkey PRIMARY KEY (id);


--
-- Name: evaluation_livreur uk4diy9aab2muyd8m2dfl05yoj9; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT uk4diy9aab2muyd8m2dfl05yoj9 UNIQUE (achat_journalier_id);


--
-- Name: bilan_mensuel uk56tjmnqpblm7du851alc14iev; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT uk56tjmnqpblm7du851alc14iev UNIQUE (poissonnerie_id, mois, annee);


--
-- Name: rapport_journalier_record ukay28drjv9uv7usxowuxkbs0t7; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT ukay28drjv9uv7usxowuxkbs0t7 UNIQUE (poissonnerie_id, date_rapport);


--
-- Name: compte_courant ukebgufpq02egng08r86sh23x6i; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT ukebgufpq02egng08r86sh23x6i UNIQUE (client_id);


--
-- Name: app_user ukexslcon9jmfy0xhclbtpf26vo; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT ukexslcon9jmfy0xhclbtpf26vo UNIQUE (phone);


--
-- Name: cloture_journaliere ukkcy5lrasix4p2qh17hns7aya3; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT ukkcy5lrasix4p2qh17hns7aya3 UNIQUE (poissonnerie_id, date);


--
-- Name: produit ukp3flguk26lkj16433geia6xx8; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT ukp3flguk26lkj16433geia6xx8 UNIQUE (nom);


--
-- Name: epargne_saving ukqsttiq0216iyjcb4h2uw8cwxe; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT ukqsttiq0216iyjcb4h2uw8cwxe UNIQUE (client_id);


--
-- Name: epargne_saving fk208qevee18krn8ec351pmfjrf; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT fk208qevee18krn8ec351pmfjrf FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: livreur fk2f6v8ktarlnwewa3en344t8p8; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.livreur
    ADD CONSTRAINT fk2f6v8ktarlnwewa3en344t8p8 FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseur(id);


--
-- Name: bilan_mensuel fk54v46awfxvqjdvuhh08h2yupd; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT fk54v46awfxvqjdvuhh08h2yupd FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: rapport_journalier_record fk5xc3810p5sn8ff872752usjqr; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT fk5xc3810p5sn8ff872752usjqr FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_compte_courant fk6slyqg6iil95y6v7mb7iiai3t; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fk6slyqg6iil95y6v7mb7iiai3t FOREIGN KEY (effectue_par_id) REFERENCES public.app_user(id);


--
-- Name: achat_journalier fk7va4sbalr59o6qnfr335mbx2g; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fk7va4sbalr59o6qnfr335mbx2g FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: notification fkagbo42kulw0dquramrmr4xj5h; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkagbo42kulw0dquramrmr4xj5h FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_saving fkao0at72gk95uo4xhnca9iqe1s; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkao0at72gk95uo4xhnca9iqe1s FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: ligne_achat fkc4ty9phm3iuxdueo3elt5t5fu; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT fkc4ty9phm3iuxdueo3elt5t5fu FOREIGN KEY (achat_journalier_id) REFERENCES public.achat_journalier(id);


--
-- Name: notification fkcxbqr6g1py0j4m9qeq44h1ju6; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkcxbqr6g1py0j4m9qeq44h1ju6 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: compte_courant fkd5soplgcg2l50nc3cafhtvks; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT fkd5soplgcg2l50nc3cafhtvks FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: evaluation_livreur fkdg5g9bwowxsuhm5n2wtw7i0nw; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkdg5g9bwowxsuhm5n2wtw7i0nw FOREIGN KEY (achat_journalier_id) REFERENCES public.achat_journalier(id);


--
-- Name: achat_journalier fkdkrnr7arco3otvydr3dws6yp4; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fkdkrnr7arco3otvydr3dws6yp4 FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseur(id);


--
-- Name: client fkdtcq2s1u9mgkg7gshsop4tvil; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkdtcq2s1u9mgkg7gshsop4tvil FOREIGN KEY (create_by_id) REFERENCES public.app_user(id);


--
-- Name: cloture_journaliere fkeps2thchmjl7nr9c4b5knhk0q; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT fkeps2thchmjl7nr9c4b5knhk0q FOREIGN KEY (cloture_par_id) REFERENCES public.app_user(id);


--
-- Name: epargne_saving fkfam213po3rt9ydtisw93c9x79; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT fkfam213po3rt9ydtisw93c9x79 FOREIGN KEY (created_by_id) REFERENCES public.app_user(id);


--
-- Name: evaluation_livreur fkgbf07m5wwl67doni7ytwcutrc; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkgbf07m5wwl67doni7ytwcutrc FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_compte_courant fkglbudo427kundgohwuql61xtf; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fkglbudo427kundgohwuql61xtf FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: bilan_mensuel fkgw5u6fhmtn1dk91dmlbep7soi; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT fkgw5u6fhmtn1dk91dmlbep7soi FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_saving fkhukhrgkxuqb57jd3tnqyj2b53; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkhukhrgkxuqb57jd3tnqyj2b53 FOREIGN KEY (saving_id) REFERENCES public.epargne_saving(id);


--
-- Name: cloture_journaliere fkkm0otfscswwkn4655faii2ac4; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT fkkm0otfscswwkn4655faii2ac4 FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: evaluation_livreur fkkpnewo8na941btcqy9wmbixrh; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkkpnewo8na941btcqy9wmbixrh FOREIGN KEY (livreur_id) REFERENCES public.livreur(id);


--
-- Name: ligne_achat fklc71754ngp8f0m1mqh8o27duy; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT fklc71754ngp8f0m1mqh8o27duy FOREIGN KEY (produit_id) REFERENCES public.produit(id);


--
-- Name: app_user fkn0x3bn8njtqvcriv1ixw3lagw; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fkn0x3bn8njtqvcriv1ixw3lagw FOREIGN KEY (default_poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: client fknd5od0ba0tna5lvns8y6htgah; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fknd5od0ba0tna5lvns8y6htgah FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_saving fkobjwynn212e9m1t93fcocui9a; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkobjwynn212e9m1t93fcocui9a FOREIGN KEY (effectue_par_id) REFERENCES public.app_user(id);


--
-- Name: employe fkp1wqmjq72mqn8dbfln28rcbl2; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fkp1wqmjq72mqn8dbfln28rcbl2 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: compte_courant fkq47ki93x94wrcv63kddbssny4; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT fkq47ki93x94wrcv63kddbssny4 FOREIGN KEY (created_by_id) REFERENCES public.app_user(id);


--
-- Name: achat_journalier fkrsku8gnxpgttcunot0s18esud; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fkrsku8gnxpgttcunot0s18esud FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_compte_courant fks68ygshjubgchpj8oqe6grdk2; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fks68ygshjubgchpj8oqe6grdk2 FOREIGN KEY (compte_courant_id) REFERENCES public.compte_courant(id);


--
-- Name: employe fksady8dihp5lrk4gdu4978ucgc; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fksady8dihp5lrk4gdu4978ucgc FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO fishcam_user;


--
-- PostgreSQL database dump complete
--

\unrestrict JrckLJ3PICEBfhwwjUjQY9PBDpkMZtnbep5Puv8j4NK96TwefVXaywgDFzs6J16

