--
-- PostgreSQL database dump
--

\restrict OAr72SILHXrIdyEh8sq2BttnBPbP8Ai8veEg5Apj4jnv7I9xTEAgKa0hMqGs5CV

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achat_journalier; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.achat_journalier (
    id bigint NOT NULL,
    cloture boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_achat date NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    fournisseur_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.achat_journalier OWNER TO fishcam_user;

--
-- Name: achat_journalier_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.achat_journalier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achat_journalier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    active boolean NOT NULL,
    avatar_path character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    role character varying(255) NOT NULL,
    scope character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    default_poissonnerie_id bigint,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'PATRON'::character varying, 'CAISSIERE'::character varying, 'ENREGISTREUR'::character varying])::text[]))),
    CONSTRAINT app_user_scope_check CHECK (((scope)::text = ANY ((ARRAY['MULTI_POISSONNERIE'::character varying, 'SINGLE_POISSONNERIE'::character varying])::text[])))
);


ALTER TABLE public.app_user OWNER TO fishcam_user;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    details character varying(1000),
    entity_id bigint,
    entity_name character varying(255) NOT NULL,
    performed_by character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone
);


ALTER TABLE public.audit_logs OWNER TO fishcam_user;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: backup_record; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.backup_record (
    id bigint NOT NULL,
    date_execution timestamp(6) without time zone NOT NULL,
    success boolean NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT backup_record_type_check CHECK (((type)::text = ANY ((ARRAY['HEBDOMADAIRE'::character varying, 'MENSUEL'::character varying])::text[])))
);


ALTER TABLE public.backup_record OWNER TO fishcam_user;

--
-- Name: backup_record_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.backup_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backup_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bilan_mensuel; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.bilan_mensuel (
    id bigint NOT NULL,
    annee integer NOT NULL,
    benefice_meilleur_jour numeric(38,2) NOT NULL,
    benefice_net_mois numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    meilleur_jour_benefice date NOT NULL,
    mois integer NOT NULL,
    montant_dettes_mois numeric(38,2) NOT NULL,
    nombre_jours_travailles integer NOT NULL,
    total_achat_mois numeric(38,2) NOT NULL,
    total_depenses_mois numeric(38,2) NOT NULL,
    total_vente_previsible_mois numeric(38,2) NOT NULL,
    total_vente_realisee numeric(38,2) NOT NULL,
    user_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.bilan_mensuel OWNER TO fishcam_user;

--
-- Name: bilan_mensuel_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.bilan_mensuel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bilan_mensuel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    active boolean,
    address character varying(255),
    cni character varying(50),
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth date,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    notes character varying(1000),
    phone character varying(20) NOT NULL,
    quartier character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    create_by_id bigint,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.client OWNER TO fishcam_user;

--
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cloture_journaliere; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.cloture_journaliere (
    id bigint NOT NULL,
    argent_caisse numeric(38,2) NOT NULL,
    autres_frais numeric(38,2) NOT NULL,
    benefice_net numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    description_autres character varying(500),
    fond_de_caisse numeric(38,2) NOT NULL,
    montant_dettes_jour numeric(38,2) NOT NULL,
    montant_rembourse_jour numeric(38,2) NOT NULL,
    nombre_dettes_jour integer NOT NULL,
    ration numeric(38,2) NOT NULL,
    total_achat numeric(38,2) NOT NULL,
    total_depenses numeric(38,2) NOT NULL,
    total_vente_previsible numeric(38,2) NOT NULL,
    transport numeric(38,2) NOT NULL,
    vente_realisee numeric(38,2) NOT NULL,
    cloture_par_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.cloture_journaliere OWNER TO fishcam_user;

--
-- Name: cloture_journaliere_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.cloture_journaliere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cloture_journaliere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compte_courant; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.compte_courant (
    id bigint NOT NULL,
    date_ouverture timestamp(6) without time zone NOT NULL,
    limite_credit_max numeric(10,2) NOT NULL,
    solde numeric(10,2) NOT NULL,
    statut character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id bigint,
    CONSTRAINT compte_courant_statut_check CHECK (((statut)::text = ANY ((ARRAY['ACTIF'::character varying, 'SUSPENDU'::character varying, 'BLOQUE'::character varying])::text[])))
);


ALTER TABLE public.compte_courant OWNER TO fishcam_user;

--
-- Name: compte_courant_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.compte_courant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compte_courant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employe; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.employe (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(50) NOT NULL,
    poste character varying(50) NOT NULL,
    prenom character varying(50) NOT NULL,
    salaire numeric(38,2) NOT NULL,
    telephone character varying(20),
    updated_at timestamp(6) without time zone NOT NULL,
    poissonnerie_id bigint NOT NULL,
    user_id bigint
);


ALTER TABLE public.employe OWNER TO fishcam_user;

--
-- Name: employe_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.employe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: epargne_saving; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.epargne_saving (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_balance numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id bigint
);


ALTER TABLE public.epargne_saving OWNER TO fishcam_user;

--
-- Name: epargne_saving_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.epargne_saving ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.epargne_saving_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_livreur; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.evaluation_livreur (
    id bigint NOT NULL,
    commentaire character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    date_evaluation date NOT NULL,
    probleme_signale boolean NOT NULL,
    qualite_produit integer NOT NULL,
    respect_poids integer NOT NULL,
    achat_journalier_id bigint NOT NULL,
    livreur_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.evaluation_livreur OWNER TO fishcam_user;

--
-- Name: evaluation_livreur_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.evaluation_livreur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_livreur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fournisseur; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.fournisseur (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(255) NOT NULL,
    telephone character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    ville character varying(100)
);


ALTER TABLE public.fournisseur OWNER TO fishcam_user;

--
-- Name: fournisseur_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.fournisseur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fournisseur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ligne_achat; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.ligne_achat (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    montant_carton numeric(38,2) NOT NULL,
    poids_kg numeric(38,2) NOT NULL,
    prix_unitaire_carton numeric(38,2) NOT NULL,
    prix_vente_kilo numeric(38,2) NOT NULL,
    quantite_cartons integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    achat_journalier_id bigint NOT NULL,
    produit_id bigint NOT NULL
);


ALTER TABLE public.ligne_achat OWNER TO fishcam_user;

--
-- Name: ligne_achat_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.ligne_achat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ligne_achat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livreur; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.livreur (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(255) NOT NULL,
    prenom character varying(255) NOT NULL,
    telephone character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    fournisseur_id bigint NOT NULL
);


ALTER TABLE public.livreur OWNER TO fishcam_user;

--
-- Name: livreur_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.livreur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livreur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(2500) NOT NULL,
    read boolean NOT NULL,
    type character varying(255) NOT NULL,
    poissonnerie_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['COMPTE_COURANT_ALERTE'::character varying, 'COMPTE_SOLDE'::character varying, 'RAPPORT_JOURNALIER'::character varying, 'INFO'::character varying])::text[])))
);


ALTER TABLE public.notification OWNER TO fishcam_user;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poissonnerie; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.poissonnerie (
    id bigint NOT NULL,
    active boolean NOT NULL,
    address character varying(225),
    created_at timestamp(6) without time zone NOT NULL,
    fond_de_caisse_defaut numeric(38,2) NOT NULL,
    loyer numeric(38,2) NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20),
    pret_actif boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.poissonnerie OWNER TO fishcam_user;

--
-- Name: poissonnerie_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.poissonnerie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.poissonnerie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produit; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.produit (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(100) NOT NULL,
    poids_par_carton numeric(38,2) NOT NULL,
    unite character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT produit_unite_check CHECK (((unite)::text = 'KG'::text))
);


ALTER TABLE public.produit OWNER TO fishcam_user;

--
-- Name: produit_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.produit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rapport_journalier_record; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.rapport_journalier_record (
    id bigint NOT NULL,
    date_rapport date NOT NULL,
    generated_at timestamp(6) without time zone,
    poissonnerie_id bigint NOT NULL
);


ALTER TABLE public.rapport_journalier_record OWNER TO fishcam_user;

--
-- Name: rapport_journalier_record_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.rapport_journalier_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rapport_journalier_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_compte_courant; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.transaction_compte_courant (
    id bigint NOT NULL,
    description character varying(500),
    montant numeric(10,2) NOT NULL,
    notes character varying(1000),
    solde_apres numeric(10,2) NOT NULL,
    solde_precedent numeric(10,2) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    compte_courant_id bigint NOT NULL,
    effectue_par_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL,
    CONSTRAINT transaction_compte_courant_type_check CHECK (((type)::text = ANY ((ARRAY['EMPRUNT'::character varying, 'REMBOURSEMENT'::character varying])::text[])))
);


ALTER TABLE public.transaction_compte_courant OWNER TO fishcam_user;

--
-- Name: transaction_compte_courant_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.transaction_compte_courant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_compte_courant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_saving; Type: TABLE; Schema: public; Owner: fishcam_user
--

CREATE TABLE public.transaction_saving (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    effectue_par_id bigint,
    saving_id bigint NOT NULL,
    poissonnerie_id bigint,
    CONSTRAINT transaction_saving_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOT'::character varying, 'RETRAIT'::character varying])::text[])))
);


ALTER TABLE public.transaction_saving OWNER TO fishcam_user;

--
-- Name: transaction_saving_id_seq; Type: SEQUENCE; Schema: public; Owner: fishcam_user
--

ALTER TABLE public.transaction_saving ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_saving_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: achat_journalier; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.achat_journalier (id, cloture, created_at, date_achat, updated_at, user_id, fournisseur_id, poissonnerie_id) FROM stdin;
1	f	2026-06-10 07:44:51.997122	2026-06-10	2026-06-10 07:44:51.997939	3	2	1
2	f	2026-06-10 11:59:01.135928	2026-06-10	2026-06-10 11:59:01.135958	2	2	1
3	t	2026-06-10 12:00:36.627346	2026-06-10	2026-06-10 12:04:31.412797	2	2	1
4	f	2026-06-10 14:44:40.800055	2026-06-10	2026-06-10 14:44:40.800112	2	1	1
5	f	2026-06-10 14:59:04.541434	2026-06-10	2026-06-10 14:59:04.541499	2	1	2
6	f	2026-06-12 16:39:23.320783	2026-06-12	2026-06-12 16:39:23.320852	4	1	1
7	f	2026-06-12 17:07:56.077742	2026-06-12	2026-06-12 17:07:56.077774	3	1	1
8	f	2026-06-12 17:08:24.611545	2026-06-12	2026-06-12 17:08:24.611602	3	1	1
9	f	2026-06-12 17:08:48.122133	2026-06-12	2026-06-12 17:08:48.122175	3	1	1
10	f	2026-06-12 17:09:06.203919	2026-06-12	2026-06-12 17:09:06.203963	3	1	1
11	f	2026-06-12 19:14:55.051294	2026-06-12	2026-06-12 19:14:55.051335	2	1	2
12	f	2026-06-13 07:43:44.959067	2026-06-13	2026-06-13 07:43:44.959123	2	1	1
13	t	2026-06-14 15:07:10.87758	2026-06-14	2026-06-14 15:08:22.048673	2	1	1
14	f	2026-06-15 14:38:10.598538	2026-06-15	2026-06-15 14:38:10.599611	4	1	1
\.


--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.app_user (id, active, avatar_path, created_at, first_name, last_name, password, phone, role, scope, updated_at, default_poissonnerie_id) FROM stdin;
1	t	\N	2026-06-07 15:43:16.02171	Super	Admin	$2a$10$8kbQlOkU62UkYg0PbTBzouYJaWvOi8BJShz38tQw0Zg.OxM3q36SW	692087724	SUPER_ADMIN	MULTI_POISSONNERIE	2026-06-07 15:43:16.021772	1
2	t	\N	2026-06-07 15:43:16.43918	Theophile	FOSSO	$2a$10$McoRxULCR35zzCvQztvSU.vknakkyRFUmq9qQKWm33kBF/AKn0bCK	676028800	PATRON	MULTI_POISSONNERIE	2026-06-07 15:43:16.439242	1
4	t	\N	2026-06-07 15:43:17.328844	Christine	Inconnu	$2a$10$TSCDYD1bDrIXH3g2M3L6Ku2G4Dm/vsA.NjhlJkjoqvh.WWcmZINLC	655032752	ENREGISTREUR	MULTI_POISSONNERIE	2026-06-16 16:21:05.390028	1
3	t	\N	2026-06-07 15:43:16.903859	Alerte	DJOKO	$2a$10$tUKYHdGZjnMd2WogJuVljun41sYH.hT6hQooP4eCDcEhKxZEfWJEu	690950871	CAISSIERE	MULTI_POISSONNERIE	2026-06-16 16:51:09.119247	1
\.


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.audit_logs (id, action, details, entity_id, entity_name, performed_by, "timestamp") FROM stdin;
1	UPDATE	Action executed via method: updateClient	1	Client	676028800	2026-06-07 16:38:06.024794
2	UPDATE	Action executed via method: updateClient	2	Client	676028800	2026-06-07 16:43:29.827366
3	UPDATE	Action executed via method: updateClient	1	Client	676028800	2026-06-07 16:43:46.409446
4	EMPRUNT	Action executed via method: enregistrerEmprunt	2	CompteCourant	655032752	2026-06-07 17:03:49.88762
5	UPDATE	Action executed via method: updateClient	3	Client	676028800	2026-06-07 17:19:00.27652
6	REMBOURSEMENT	Action executed via method: enregistrerRemboursement	3	CompteCourant	676028800	2026-06-07 17:19:48.75855
7	DEPOT	Action executed via method: deposer	3	Epargne	676028800	2026-06-07 17:20:05.97018
8	RETRAIT	Action executed via method: retirer	3	Epargne	676028800	2026-06-07 17:20:13.648184
9	CREATE	Action executed via method: createFacture	1	AchatJournalier	690950871	2026-06-10 07:44:52.157299
10	ADD Ligne	Action executed via method: addLigne	1	AchatJournalier	690950871	2026-06-10 07:44:52.740529
11	CREATE	Action executed via method: createFacture	2	AchatJournalier	676028800	2026-06-10 11:59:01.150269
12	ADD Ligne	Action executed via method: addLigne	2	AchatJournalier	676028800	2026-06-10 11:59:01.254841
13	ADD Ligne	Action executed via method: addLigne	3	AchatJournalier	676028800	2026-06-10 11:59:01.319961
14	CREATE	Action executed via method: createFacture	3	AchatJournalier	676028800	2026-06-10 12:00:36.639412
15	ADD Ligne	Action executed via method: addLigne	4	AchatJournalier	676028800	2026-06-10 12:00:36.758692
16	ADD Ligne	Action executed via method: addLigne	5	AchatJournalier	676028800	2026-06-10 12:00:36.893451
17	CLOTURE	Action executed via method: cloturerFacture	3	AchatJournalier	676028800	2026-06-10 12:04:31.406575
18	CREATE	Action executed via method: createFacture	4	AchatJournalier	676028800	2026-06-10 14:44:40.834957
19	ADD Ligne	Action executed via method: addLigne	6	AchatJournalier	676028800	2026-06-10 14:44:41.015323
20	ADD Ligne	Action executed via method: addLigne	7	AchatJournalier	676028800	2026-06-10 14:44:41.131087
21	ADD Ligne	Action executed via method: addLigne	8	AchatJournalier	676028800	2026-06-10 14:45:08.207286
22	CREATE	Action executed via method: createFacture	5	AchatJournalier	676028800	2026-06-10 14:59:04.656471
23	ADD Ligne	Action executed via method: addLigne	9	AchatJournalier	676028800	2026-06-10 14:59:04.903054
24	ADD Ligne	Action executed via method: addLigne	10	AchatJournalier	676028800	2026-06-10 14:59:05.045976
25	EMPRUNT	Action executed via method: enregistrerEmprunt	1	CompteCourant	676028800	2026-06-11 18:36:28.833457
26	EMPRUNT	Action executed via method: enregistrerEmprunt	1	CompteCourant	690950871	2026-06-11 19:54:26.544991
27	DELETE	Action executed via method: deleteLigne	\N	AchatJournalier	692087724	2026-06-12 14:50:39.744861
28	REMBOURSEMENT	Action executed via method: enregistrerRemboursement	2	CompteCourant	690950871	2026-06-12 16:05:26.196084
29	CREATE	Action executed via method: createFacture	6	AchatJournalier	655032752	2026-06-12 16:39:23.351029
30	ADD Ligne	Action executed via method: addLigne	11	AchatJournalier	655032752	2026-06-12 16:39:23.924047
31	ADD Ligne	Action executed via method: addLigne	12	AchatJournalier	655032752	2026-06-12 16:39:24.026336
32	CREATE	Action executed via method: createFacture	7	AchatJournalier	690950871	2026-06-12 17:07:56.095405
33	ADD Ligne	Action executed via method: addLigne	13	AchatJournalier	690950871	2026-06-12 17:07:56.230232
34	ADD Ligne	Action executed via method: addLigne	14	AchatJournalier	690950871	2026-06-12 17:07:56.363609
35	ADD Ligne	Action executed via method: addLigne	15	AchatJournalier	690950871	2026-06-12 17:07:56.454712
36	CREATE	Action executed via method: createFacture	8	AchatJournalier	690950871	2026-06-12 17:08:24.627736
37	ADD Ligne	Action executed via method: addLigne	16	AchatJournalier	690950871	2026-06-12 17:08:24.737657
38	CREATE	Action executed via method: createFacture	9	AchatJournalier	690950871	2026-06-12 17:08:48.132351
39	ADD Ligne	Action executed via method: addLigne	17	AchatJournalier	690950871	2026-06-12 17:08:48.265998
40	CREATE	Action executed via method: createFacture	10	AchatJournalier	690950871	2026-06-12 17:09:06.256513
41	ADD Ligne	Action executed via method: addLigne	18	AchatJournalier	690950871	2026-06-12 17:09:06.406295
42	CLOTURE	Action executed via method: cloturer	1	ClotureJournaliere	676028800	2026-06-12 18:59:07.0837
43	CREATE	Action executed via method: createFacture	11	AchatJournalier	676028800	2026-06-12 19:14:55.06666
44	ADD Ligne	Action executed via method: addLigne	19	AchatJournalier	676028800	2026-06-12 19:14:55.172902
45	ADD Ligne	Action executed via method: addLigne	20	AchatJournalier	676028800	2026-06-12 19:14:55.257157
46	CLOTURE	Action executed via method: cloturer	2	ClotureJournaliere	676028800	2026-06-12 19:15:34.357715
47	CREATE	Action executed via method: createFacture	12	AchatJournalier	676028800	2026-06-13 07:43:45.00202
48	ADD Ligne	Action executed via method: addLigne	21	AchatJournalier	676028800	2026-06-13 07:43:45.251274
49	EMPRUNT	Action executed via method: enregistrerEmprunt	2	CompteCourant	655032752	2026-06-13 16:12:35.628011
50	DEPOT	Action executed via method: deposer	2	Epargne	690950871	2026-06-13 17:55:59.124544
51	EMPRUNT	Action executed via method: enregistrerEmprunt	2	CompteCourant	690950871	2026-06-13 17:56:10.032255
52	RETRAIT	Action executed via method: retirer	2	Epargne	690950871	2026-06-13 17:56:44.744827
53	UPDATE	Action executed via method: updateProduit	6	Produit	655032752	2026-06-14 14:32:09.889052
54	CREATE	Action executed via method: createFacture	13	AchatJournalier	676028800	2026-06-14 15:07:10.903782
55	ADD Ligne	Action executed via method: addLigne	22	AchatJournalier	676028800	2026-06-14 15:07:11.126923
56	CLOTURE	Action executed via method: cloturerFacture	13	AchatJournalier	676028800	2026-06-14 15:08:22.040788
57	DELETE	Action executed via method: deleteFournisseur	\N	Fournisseur	676028800	2026-06-14 20:30:10.234796
58	REACTIVATE	Action executed via method: reactivateFournisseur	2	Fournisseur	676028800	2026-06-15 06:41:03.815558
59	DELETE	Action executed via method: deleteFournisseur	\N	Fournisseur	676028800	2026-06-15 07:32:37.763856
60	REACTIVATE	Action executed via method: reactivateFournisseur	2	Fournisseur	676028800	2026-06-15 07:32:42.925693
61	CREATE	Action executed via method: createFacture	14	AchatJournalier	655032752	2026-06-15 14:38:10.677387
62	ADD Ligne	Action executed via method: addLigne	23	AchatJournalier	655032752	2026-06-15 14:38:10.905437
63	DELETE	Action executed via method: deleteFournisseur	\N	Fournisseur	676028800	2026-06-15 14:50:51.283393
64	REACTIVATE	Action executed via method: reactivateFournisseur	2	Fournisseur	676028800	2026-06-15 14:50:53.118206
65	DELETE	Action executed via method: deleteProduit	\N	Produit	676028800	2026-06-15 14:58:35.68414
66	CREATE	Action executed via method: createEvaluation	1	EvaluationLivreur	690950871	2026-06-15 15:18:41.208652
67	DELETE	Action executed via method: deleteProduit	\N	Produit	676028800	2026-06-15 16:17:03.58111
68	REACTIVATE	Action executed via method: reactivateProduit	7	Produit	676028800	2026-06-15 16:34:33.336436
69	REACTIVATE	Action executed via method: reactivateProduit	5	Produit	676028800	2026-06-15 16:34:35.595764
70	UPDATE	Action executed via method: updateUser	3	User	676028800	2026-06-15 18:55:18.025515
71	EMPRUNT	Action executed via method: enregistrerEmprunt	2	CompteCourant	690950871	2026-06-15 19:29:16.173846
72	REMBOURSEMENT	Action executed via method: enregistrerRemboursement	2	CompteCourant	692087724	2026-06-16 07:01:45.859749
73	DELETE	Action executed via method: deleteUser	\N	User	692087724	2026-06-16 14:55:50.411412
74	REACTIVATE	Opération effectuée via : reactivateUser	4	User	Super Admin	2026-06-16 16:20:56.904114
75	DELETE	Opération effectuée via : deleteUser	\N	User	Super Admin	2026-06-16 16:21:02.300567
76	REACTIVATE	Opération effectuée via : reactivateUser	4	User	Super Admin	2026-06-16 16:21:05.383481
77	UPDATE	Opération effectuée via : updateUser	3	User	Super Admin	2026-06-16 16:50:20.658289
78	UPDATE	Opération effectuée via : updateUser	3	User	Super Admin	2026-06-16 16:51:09.11262
\.


--
-- Data for Name: backup_record; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.backup_record (id, date_execution, success, type) FROM stdin;
\.


--
-- Data for Name: bilan_mensuel; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.bilan_mensuel (id, annee, benefice_meilleur_jour, benefice_net_mois, created_at, meilleur_jour_benefice, mois, montant_dettes_mois, nombre_jours_travailles, total_achat_mois, total_depenses_mois, total_vente_previsible_mois, total_vente_realisee, user_id, poissonnerie_id) FROM stdin;
\.


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.client (id, active, address, cni, created_at, date_of_birth, first_name, last_name, notes, phone, quartier, updated_at, create_by_id, poissonnerie_id) FROM stdin;
2	t	Carrefour	456123	2026-06-07 15:43:17.60899	2026-04-08	Papa	Simon	\N	690000012	Deido	2026-06-07 16:43:29.836477	2	1
1	t	Derrière le marché	456123	2026-06-07 15:43:17.541954	2026-04-30	Maman	Clementine	\N	690000011	Akwa	2026-06-07 16:43:46.416075	2	1
3	t	Avenue principale	123456	2026-06-07 15:43:17.658144	2026-06-04	Tante	Marie	\N	690000013	Bonamoussadi	2026-06-07 17:19:00.286105	2	2
\.


--
-- Data for Name: cloture_journaliere; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.cloture_journaliere (id, argent_caisse, autres_frais, benefice_net, created_at, date, description_autres, fond_de_caisse, montant_dettes_jour, montant_rembourse_jour, nombre_dettes_jour, ration, total_achat, total_depenses, total_vente_previsible, transport, vente_realisee, cloture_par_id, poissonnerie_id) FROM stdin;
1	175000.00	0.00	1500.00	2026-06-12 18:59:07.034648	2026-06-12		10000.00	26000.00	4000.00	2	1500.00	157000.00	6500.00	173000.00	5000.00	165000.00	2	1
2	150000.00	0.00	92000.00	2026-06-12 19:15:34.347592	2026-06-12		10000.00	5000.00	0.00	1	2000.00	41000.00	7000.00	45500.00	5000.00	140000.00	2	2
\.


--
-- Data for Name: compte_courant; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.compte_courant (id, date_ouverture, limite_credit_max, solde, statut, updated_at, client_id, created_by_id) FROM stdin;
3	2026-06-07 15:43:17.67623	50000.00	-5000.00	BLOQUE	2026-06-07 17:19:48.765364	3	\N
1	2026-06-07 15:43:17.562582	50000.00	-25000.00	ACTIF	2026-06-11 19:54:26.552037	1	\N
2	2026-06-07 15:43:17.624631	20000.00	-3500.00	ACTIF	2026-06-16 07:01:45.890458	2	\N
\.


--
-- Data for Name: employe; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.employe (id, actif, created_at, nom, poste, prenom, salaire, telephone, updated_at, poissonnerie_id, user_id) FROM stdin;
\.


--
-- Data for Name: epargne_saving; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.epargne_saving (id, created_at, current_balance, updated_at, client_id, created_by_id) FROM stdin;
1	2026-06-07 15:43:17.585002	25000.00	2026-06-07 15:43:17.585112	1	2
3	2026-06-07 15:43:17.691051	1000.00	2026-06-07 17:20:13.653632	3	2
2	2026-06-07 15:43:17.642451	103000.00	2026-06-13 17:56:44.766193	2	2
\.


--
-- Data for Name: evaluation_livreur; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.evaluation_livreur (id, commentaire, created_at, date_evaluation, probleme_signale, qualite_produit, respect_poids, achat_journalier_id, livreur_id, user_id) FROM stdin;
1	\N	2026-06-15 15:18:41.182884	2026-06-15	f	3	3	14	1	3
\.


--
-- Data for Name: fournisseur; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.fournisseur (id, actif, created_at, nom, telephone, updated_at, ville) FROM stdin;
1	t	2026-06-07 15:43:17.352569	CONGELCAM SA	670000000	2026-06-07 15:43:17.352636	Douala
2	t	2026-06-07 15:43:17.369044	QUEEN FISH	690000000	2026-06-15 14:50:53.122494	Yaoundé
\.


--
-- Data for Name: ligne_achat; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.ligne_achat (id, created_at, montant_carton, poids_kg, prix_unitaire_carton, prix_vente_kilo, quantite_cartons, updated_at, achat_journalier_id, produit_id) FROM stdin;
1	2026-06-10 07:44:52.723177	25000.00	20.00	25000.00	1500.00	1	2026-06-10 07:44:52.723227	1	1
2	2026-06-10 11:59:01.244649	28500.00	21.00	28500.00	1400.00	1	2026-06-10 11:59:01.244684	2	2
3	2026-06-10 11:59:01.313636	17000.00	20.00	17000.00	950.00	1	2026-06-10 11:59:01.313673	2	4
4	2026-06-10 12:00:36.748141	17000.00	10.00	17000.00	950.00	1	2026-06-10 12:00:36.748175	3	4
5	2026-06-10 12:00:36.87345	28500.00	20.00	28500.00	1500.00	1	2026-06-10 12:00:36.873491	3	2
7	2026-06-10 14:44:41.119854	15000.00	10.00	15000.00	1600.00	1	2026-06-10 14:44:41.1199	4	6
8	2026-06-10 14:45:08.198039	16000.00	15.00	16000.00	1700.00	1	2026-06-10 14:45:08.198081	4	3
9	2026-06-10 14:59:04.876956	15000.00	10.00	15000.00	1600.00	1	2026-06-10 14:59:04.877007	5	6
10	2026-06-10 14:59:05.032246	28500.00	20.00	28500.00	1500.00	1	2026-06-10 14:59:05.032313	5	2
11	2026-06-12 16:39:23.91076	15000.00	10.00	15000.00	1600.00	1	2026-06-12 16:39:23.910855	6	6
12	2026-06-12 16:39:24.01654	25000.00	20.00	25000.00	1500.00	1	2026-06-12 16:39:24.016579	6	1
13	2026-06-12 17:07:56.218647	15000.00	10.00	15000.00	1600.00	1	2026-06-12 17:07:56.218699	7	6
14	2026-06-12 17:07:56.351334	26000.00	20.00	26000.00	1500.00	1	2026-06-12 17:07:56.35138	7	1
15	2026-06-12 17:07:56.447932	27000.00	20.00	27000.00	1500.00	1	2026-06-12 17:07:56.447976	7	1
16	2026-06-12 17:08:24.728147	16000.00	10.00	16000.00	1600.00	1	2026-06-12 17:08:24.728204	8	6
17	2026-06-12 17:08:48.256328	19000.00	10.00	19000.00	1950.00	1	2026-06-12 17:08:48.256462	9	6
18	2026-06-12 17:09:06.392874	14000.00	10.00	14000.00	1550.00	1	2026-06-12 17:09:06.392922	10	6
19	2026-06-12 19:14:55.162164	14000.00	10.00	14000.00	1550.00	1	2026-06-12 19:14:55.1622	11	6
20	2026-06-12 19:14:55.247117	27000.00	20.00	27000.00	1500.00	1	2026-06-12 19:14:55.247148	11	1
21	2026-06-13 07:43:45.226953	14000.00	10.00	14000.00	1550.00	1	2026-06-13 07:43:45.227024	12	6
22	2026-06-14 15:07:11.109237	14000.00	15.00	14000.00	1550.00	1	2026-06-14 15:07:11.109281	13	6
23	2026-06-15 14:38:10.895459	15000.00	20.00	15000.00	1600.00	1	2026-06-15 14:38:10.895506	14	5
\.


--
-- Data for Name: livreur; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.livreur (id, actif, created_at, nom, prenom, telephone, updated_at, fournisseur_id) FROM stdin;
1	t	2026-06-07 15:43:17.392217	Ndjana	Paul	671000001	2026-06-07 15:43:17.39231	1
2	t	2026-06-07 15:43:17.407159	Talla	Serge	671000002	2026-06-07 15:43:17.407225	2
\.


--
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.notification (id, created_at, message, read, type, poissonnerie_id, user_id) FROM stdin;
1	2026-06-07 15:43:18.165627	Alerte : journée non clôturée\n\nLe rapport du 2026-06-06 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
2	2026-06-07 15:43:18.184977	Alerte : journée non clôturée\n\nLe rapport du 2026-06-06 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
3	2026-06-07 15:43:18.206491	Alerte : journée non clôturée\n\nLe rapport du 2026-06-06 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
5	2026-06-07 15:43:18.312958	Alerte : journée non clôturée\n\nLe rapport du 2026-06-05 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
6	2026-06-07 15:43:18.344322	Alerte : journée non clôturée\n\nLe rapport du 2026-06-05 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
7	2026-06-07 15:43:18.370057	Alerte : journée non clôturée\n\nLe rapport du 2026-06-05 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
9	2026-06-07 15:43:18.503157	Alerte : journée non clôturée\n\nLe rapport du 2026-06-04 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
10	2026-06-07 15:43:18.540051	Alerte : journée non clôturée\n\nLe rapport du 2026-06-04 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
13	2026-06-07 15:43:18.693829	Alerte : journée non clôturée\n\nLe rapport du 2026-06-03 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
14	2026-06-07 15:43:18.72323	Alerte : journée non clôturée\n\nLe rapport du 2026-06-03 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
15	2026-06-07 15:43:18.751687	Alerte : journée non clôturée\n\nLe rapport du 2026-06-03 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
17	2026-06-07 15:43:18.831122	Alerte : journée non clôturée\n\nLe rapport du 2026-06-02 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
18	2026-06-07 15:43:18.859865	Alerte : journée non clôturée\n\nLe rapport du 2026-06-02 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
19	2026-06-07 15:43:18.890955	Alerte : journée non clôturée\n\nLe rapport du 2026-06-02 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
21	2026-06-07 15:43:18.972587	Alerte : journée non clôturée\n\nLe rapport du 2026-06-01 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
22	2026-06-07 15:43:18.997249	Alerte : journée non clôturée\n\nLe rapport du 2026-06-01 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
23	2026-06-07 15:43:19.017519	Alerte : journée non clôturée\n\nLe rapport du 2026-06-01 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
25	2026-06-07 15:43:19.096393	Alerte : journée non clôturée\n\nLe rapport du 2026-05-31 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
26	2026-06-07 15:43:19.122822	Alerte : journée non clôturée\n\nLe rapport du 2026-05-31 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
27	2026-06-07 15:43:19.160638	Alerte : journée non clôturée\n\nLe rapport du 2026-05-31 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
11	2026-06-07 15:43:18.585318	Alerte : journée non clôturée\n\nLe rapport du 2026-06-04 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	3
29	2026-06-08 03:35:06.761756	Rapport du 8 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	1
30	2026-06-08 03:35:06.770066	Rapport du 8 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	2
31	2026-06-08 03:35:06.775029	Rapport du 8 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	3
33	2026-06-10 12:12:03.684569	Rapport du 10 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	1
34	2026-06-10 12:12:03.69356	Rapport du 10 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	2
35	2026-06-10 12:12:03.698163	Rapport du 10 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	3
37	2026-06-10 13:25:45.511057	Alerte : journée non clôturée\n\nLe rapport du 2026-06-09 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
38	2026-06-10 13:25:45.644094	Alerte : journée non clôturée\n\nLe rapport du 2026-06-09 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
39	2026-06-10 13:25:45.687757	Alerte : journée non clôturée\n\nLe rapport du 2026-06-09 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
41	2026-06-10 13:25:45.821877	Alerte : journée non clôturée\n\nLe rapport du 2026-06-07 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
42	2026-06-10 13:25:45.849127	Alerte : journée non clôturée\n\nLe rapport du 2026-06-07 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
43	2026-06-10 13:25:45.873149	Alerte : journée non clôturée\n\nLe rapport du 2026-06-07 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
45	2026-06-11 15:52:14.125456	Rapport du 11 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	1
46	2026-06-11 15:52:14.541884	Rapport du 11 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	2
47	2026-06-11 15:52:14.555371	Rapport du 11 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	f	RAPPORT_JOURNALIER	1	3
49	2026-06-11 18:36:28.793003	Alerte compte courant : Augmentation significative\nClient : Maman Clementine\nSolde actuel : -20000.00 FCFA	f	COMPTE_COURANT_ALERTE	1	1
50	2026-06-11 18:36:28.806143	Alerte compte courant : Augmentation significative\nClient : Maman Clementine\nSolde actuel : -20000.00 FCFA	f	COMPTE_COURANT_ALERTE	1	2
51	2026-06-11 19:54:26.532388	Alerte compte courant : Augmentation significative\nClient : Maman Clementine\nSolde actuel : -25000.00 FCFA	f	COMPTE_COURANT_ALERTE	1	1
52	2026-06-11 19:54:26.537712	Alerte compte courant : Augmentation significative\nClient : Maman Clementine\nSolde actuel : -25000.00 FCFA	f	COMPTE_COURANT_ALERTE	1	2
53	2026-06-13 07:40:20.667498	Alerte : journée non clôturée\n\nLe rapport du 2026-06-12 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
54	2026-06-13 07:40:20.794794	Alerte : journée non clôturée\n\nLe rapport du 2026-06-12 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
55	2026-06-13 07:40:20.856826	Alerte : journée non clôturée\n\nLe rapport du 2026-06-12 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
57	2026-06-13 19:00:00.795129	Rapport du 13 juin 2026\n\nEmprunts : 2 transactions - 2500 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : -2500 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	1
58	2026-06-13 19:00:01.074993	Rapport du 13 juin 2026\n\nEmprunts : 2 transactions - 2500 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : -2500 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	2
59	2026-06-13 19:00:01.094638	Rapport du 13 juin 2026\n\nEmprunts : 2 transactions - 2500 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : -2500 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	3
4	2026-06-07 15:43:18.24127	Alerte : journée non clôturée\n\nLe rapport du 2026-06-06 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
8	2026-06-07 15:43:18.405362	Alerte : journée non clôturée\n\nLe rapport du 2026-06-05 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
12	2026-06-07 15:43:18.618694	Alerte : journée non clôturée\n\nLe rapport du 2026-06-04 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
16	2026-06-07 15:43:18.777642	Alerte : journée non clôturée\n\nLe rapport du 2026-06-03 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
20	2026-06-07 15:43:18.912225	Alerte : journée non clôturée\n\nLe rapport du 2026-06-02 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
24	2026-06-07 15:43:19.03657	Alerte : journée non clôturée\n\nLe rapport du 2026-06-01 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
28	2026-06-07 15:43:19.186189	Alerte : journée non clôturée\n\nLe rapport du 2026-05-31 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
32	2026-06-08 03:35:06.780369	Rapport du 8 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	t	RAPPORT_JOURNALIER	1	4
36	2026-06-10 12:12:03.702027	Rapport du 10 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	t	RAPPORT_JOURNALIER	1	4
40	2026-06-10 13:25:45.726586	Alerte : journée non clôturée\n\nLe rapport du 2026-06-09 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
44	2026-06-10 13:25:45.942075	Alerte : journée non clôturée\n\nLe rapport du 2026-06-07 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
48	2026-06-11 15:52:14.567873	Rapport du 11 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 20000 FCFA	t	RAPPORT_JOURNALIER	1	4
56	2026-06-13 07:40:20.901433	Alerte : journée non clôturée\n\nLe rapport du 2026-06-12 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	t	RAPPORT_JOURNALIER	1	4
60	2026-06-13 19:00:01.107384	Rapport du 13 juin 2026\n\nEmprunts : 2 transactions - 2500 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : -2500 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	t	RAPPORT_JOURNALIER	1	4
61	2026-06-15 06:30:29.899196	Alerte : journée non clôturée\n\nLe rapport du 2026-06-14 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	1
62	2026-06-15 06:30:30.081047	Alerte : journée non clôturée\n\nLe rapport du 2026-06-14 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	2
63	2026-06-15 06:30:30.181499	Alerte : journée non clôturée\n\nLe rapport du 2026-06-14 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	3
64	2026-06-15 06:30:30.261139	Alerte : journée non clôturée\n\nLe rapport du 2026-06-14 n'a pas été généré.\nLe poste était peut-être éteint à l'heure prévue.\nVeuillez vérifier les transactions manuellement si nécessaire.	f	RAPPORT_JOURNALIER	1	4
65	2026-06-15 19:00:00.661594	Rapport du 15 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	1
66	2026-06-15 19:00:00.684051	Rapport du 15 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	2
67	2026-06-15 19:00:00.693564	Rapport du 15 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	3
68	2026-06-15 19:00:00.703356	Rapport du 15 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	4
69	2026-06-15 19:29:16.160332	Alerte compte courant : Seuil franchi\nClient : Papa Simon\nSeuil : -5000 FCFA\nSolde actuel : -8500 FCFA	f	COMPTE_COURANT_ALERTE	1	1
70	2026-06-15 19:29:16.166301	Alerte compte courant : Seuil franchi\nClient : Papa Simon\nSeuil : -5000 FCFA\nSolde actuel : -8500 FCFA	f	COMPTE_COURANT_ALERTE	1	2
71	2026-06-17 05:50:48.940511	Rapport du 17 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	1
72	2026-06-17 05:50:49.019572	Rapport du 17 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	2
73	2026-06-17 05:50:49.025901	Rapport du 17 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	4
74	2026-06-17 05:50:49.032651	Rapport du 17 juin 2026\n\nEmprunts : 0 transactions - 0 FCFA\nRemboursements : 0 transactions - 0 FCFA\nNet (R - E) : 0 FCFA\n\nComptes en dette : 2 clients\nTotal dettes actives : 28500 FCFA	f	RAPPORT_JOURNALIER	1	3
\.


--
-- Data for Name: poissonnerie; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.poissonnerie (id, active, address, created_at, fond_de_caisse_defaut, loyer, name, phone, pret_actif, updated_at) FROM stdin;
1	t	La Petite mosquée	2026-06-07 15:43:15.466986	10000.00	50000.00	FISH CAM VILLE (TEST)	676028800	t	2026-06-07 15:43:15.467116
2	t	Marché Bonamoussadi	2026-06-07 15:43:15.574591	15000.00	45000.00	Poissonnerie La Référence (Bonamoussadi)	+237690000001	f	2026-06-07 15:43:15.574668
\.


--
-- Data for Name: produit; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.produit (id, actif, created_at, nom, poids_par_carton, unite, updated_at) FROM stdin;
1	t	2026-06-07 15:43:17.425461	Maquereau 20+ (Chinchard)	20.00	KG	2026-06-07 15:43:17.425558
2	t	2026-06-07 15:43:17.44675	Maquereau 25+ (Chinchard)	20.00	KG	2026-06-07 15:43:17.446844
3	t	2026-06-07 15:43:17.467158	Bar (Grand)	15.00	KG	2026-06-07 15:43:17.467239
4	t	2026-06-07 15:43:17.482246	Bar (Moyen)	10.00	KG	2026-06-07 15:43:17.482314
6	t	2026-06-07 15:43:17.515854	Carpe	15.00	KG	2026-06-14 14:32:10.36311
7	t	2026-06-07 15:43:17.528265	Saucisse (Saucisson de mer)	10.00	KG	2026-06-15 16:34:33.471012
5	t	2026-06-07 15:43:17.5004	Silure (Machoiron)	20.00	KG	2026-06-15 16:34:35.607547
\.


--
-- Data for Name: rapport_journalier_record; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.rapport_journalier_record (id, date_rapport, generated_at, poissonnerie_id) FROM stdin;
1	2026-06-08	2026-06-08 03:35:06.789152	1
2	2026-06-08	2026-06-08 03:35:06.850256	2
3	2026-06-10	2026-06-10 12:12:03.708802	1
4	2026-06-10	2026-06-10 12:12:03.742607	2
5	2026-06-11	2026-06-11 15:52:14.593048	1
6	2026-06-11	2026-06-11 15:52:14.722432	2
7	2026-06-13	2026-06-13 19:00:01.117607	1
8	2026-06-13	2026-06-13 19:00:01.314996	2
9	2026-06-15	2026-06-15 19:00:00.730969	1
10	2026-06-15	2026-06-15 19:00:00.814586	2
11	2026-06-17	2026-06-17 05:50:49.05708	1
12	2026-06-17	2026-06-17 05:50:49.167638	2
\.


--
-- Data for Name: transaction_compte_courant; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.transaction_compte_courant (id, description, montant, notes, solde_apres, solde_precedent, transaction_date, type, compte_courant_id, effectue_par_id, poissonnerie_id) FROM stdin;
1	 	5000.00	\N	-5000.00	0.00	2026-06-07 17:03:49.835212	EMPRUNT	2	4	1
2	Remboursement cash	50000.00	\N	-5000.00	-55000.00	2026-06-07 17:19:48.746014	REMBOURSEMENT	3	2	2
3	 	5000.00	\N	-20000.00	-15000.00	2026-06-11 18:36:28.581769	EMPRUNT	1	2	1
4	 	5000.00	\N	-25000.00	-20000.00	2026-06-11 19:54:26.506222	EMPRUNT	1	3	1
5	Remboursement cash	4000.00	\N	-1000.00	-5000.00	2026-06-12 16:05:26.156631	REMBOURSEMENT	2	3	1
6	 	2000.00	\N	-3000.00	-1000.00	2026-06-13 16:12:35.537191	EMPRUNT	2	4	1
7	achat	500.00	\N	-3500.00	-3000.00	2026-06-13 17:56:10.011479	EMPRUNT	2	3	1
8	 	5000.00	\N	-8500.00	-3500.00	2026-06-15 19:29:16.115712	EMPRUNT	2	3	1
9	Remboursement cash	5000.00	\N	-3500.00	-8500.00	2026-06-16 07:01:45.761215	REMBOURSEMENT	2	1	1
\.


--
-- Data for Name: transaction_saving; Type: TABLE DATA; Schema: public; Owner: fishcam_user
--

COPY public.transaction_saving (id, amount, transaction_date, type, effectue_par_id, saving_id, poissonnerie_id) FROM stdin;
1	5000.00	2026-06-07 17:20:05.942995	DEPOT	2	3	2
2	4000.00	2026-06-07 17:20:13.637657	RETRAIT	2	3	2
3	5000.00	2026-06-13 17:55:59.033576	DEPOT	3	2	1
4	2000.00	2026-06-13 17:56:44.728185	RETRAIT	3	2	1
\.


--
-- Name: achat_journalier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.achat_journalier_id_seq', 14, true);


--
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.app_user_id_seq', 4, true);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 78, true);


--
-- Name: backup_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.backup_record_id_seq', 1, false);


--
-- Name: bilan_mensuel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.bilan_mensuel_id_seq', 1, false);


--
-- Name: client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.client_id_seq', 3, true);


--
-- Name: cloture_journaliere_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.cloture_journaliere_id_seq', 2, true);


--
-- Name: compte_courant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.compte_courant_id_seq', 3, true);


--
-- Name: employe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.employe_id_seq', 1, false);


--
-- Name: epargne_saving_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.epargne_saving_id_seq', 3, true);


--
-- Name: evaluation_livreur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.evaluation_livreur_id_seq', 1, true);


--
-- Name: fournisseur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.fournisseur_id_seq', 2, true);


--
-- Name: ligne_achat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.ligne_achat_id_seq', 23, true);


--
-- Name: livreur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.livreur_id_seq', 2, true);


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.notification_id_seq', 74, true);


--
-- Name: poissonnerie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.poissonnerie_id_seq', 2, true);


--
-- Name: produit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.produit_id_seq', 7, true);


--
-- Name: rapport_journalier_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.rapport_journalier_record_id_seq', 12, true);


--
-- Name: transaction_compte_courant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.transaction_compte_courant_id_seq', 9, true);


--
-- Name: transaction_saving_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fishcam_user
--

SELECT pg_catalog.setval('public.transaction_saving_id_seq', 4, true);


--
-- Name: achat_journalier achat_journalier_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT achat_journalier_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: backup_record backup_record_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_pkey PRIMARY KEY (id);


--
-- Name: bilan_mensuel bilan_mensuel_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT bilan_mensuel_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: cloture_journaliere cloture_journaliere_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT cloture_journaliere_pkey PRIMARY KEY (id);


--
-- Name: compte_courant compte_courant_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT compte_courant_pkey PRIMARY KEY (id);


--
-- Name: employe employe_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT employe_pkey PRIMARY KEY (id);


--
-- Name: epargne_saving epargne_saving_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT epargne_saving_pkey PRIMARY KEY (id);


--
-- Name: evaluation_livreur evaluation_livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT evaluation_livreur_pkey PRIMARY KEY (id);


--
-- Name: fournisseur fournisseur_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.fournisseur
    ADD CONSTRAINT fournisseur_pkey PRIMARY KEY (id);


--
-- Name: ligne_achat ligne_achat_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT ligne_achat_pkey PRIMARY KEY (id);


--
-- Name: livreur livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.livreur
    ADD CONSTRAINT livreur_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: poissonnerie poissonnerie_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.poissonnerie
    ADD CONSTRAINT poissonnerie_pkey PRIMARY KEY (id);


--
-- Name: produit produit_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT produit_pkey PRIMARY KEY (id);


--
-- Name: rapport_journalier_record rapport_journalier_record_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT rapport_journalier_record_pkey PRIMARY KEY (id);


--
-- Name: transaction_compte_courant transaction_compte_courant_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT transaction_compte_courant_pkey PRIMARY KEY (id);


--
-- Name: transaction_saving transaction_saving_pkey; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT transaction_saving_pkey PRIMARY KEY (id);


--
-- Name: evaluation_livreur uk4diy9aab2muyd8m2dfl05yoj9; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT uk4diy9aab2muyd8m2dfl05yoj9 UNIQUE (achat_journalier_id);


--
-- Name: bilan_mensuel uk56tjmnqpblm7du851alc14iev; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT uk56tjmnqpblm7du851alc14iev UNIQUE (poissonnerie_id, mois, annee);


--
-- Name: rapport_journalier_record ukay28drjv9uv7usxowuxkbs0t7; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT ukay28drjv9uv7usxowuxkbs0t7 UNIQUE (poissonnerie_id, date_rapport);


--
-- Name: compte_courant ukebgufpq02egng08r86sh23x6i; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT ukebgufpq02egng08r86sh23x6i UNIQUE (client_id);


--
-- Name: app_user ukexslcon9jmfy0xhclbtpf26vo; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT ukexslcon9jmfy0xhclbtpf26vo UNIQUE (phone);


--
-- Name: cloture_journaliere ukkcy5lrasix4p2qh17hns7aya3; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT ukkcy5lrasix4p2qh17hns7aya3 UNIQUE (poissonnerie_id, date);


--
-- Name: produit ukp3flguk26lkj16433geia6xx8; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT ukp3flguk26lkj16433geia6xx8 UNIQUE (nom);


--
-- Name: epargne_saving ukqsttiq0216iyjcb4h2uw8cwxe; Type: CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT ukqsttiq0216iyjcb4h2uw8cwxe UNIQUE (client_id);


--
-- Name: epargne_saving fk208qevee18krn8ec351pmfjrf; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT fk208qevee18krn8ec351pmfjrf FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: livreur fk2f6v8ktarlnwewa3en344t8p8; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.livreur
    ADD CONSTRAINT fk2f6v8ktarlnwewa3en344t8p8 FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseur(id);


--
-- Name: bilan_mensuel fk54v46awfxvqjdvuhh08h2yupd; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT fk54v46awfxvqjdvuhh08h2yupd FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: rapport_journalier_record fk5xc3810p5sn8ff872752usjqr; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT fk5xc3810p5sn8ff872752usjqr FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_compte_courant fk6slyqg6iil95y6v7mb7iiai3t; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fk6slyqg6iil95y6v7mb7iiai3t FOREIGN KEY (effectue_par_id) REFERENCES public.app_user(id);


--
-- Name: achat_journalier fk7va4sbalr59o6qnfr335mbx2g; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fk7va4sbalr59o6qnfr335mbx2g FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: notification fkagbo42kulw0dquramrmr4xj5h; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkagbo42kulw0dquramrmr4xj5h FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_saving fkao0at72gk95uo4xhnca9iqe1s; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkao0at72gk95uo4xhnca9iqe1s FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: ligne_achat fkc4ty9phm3iuxdueo3elt5t5fu; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT fkc4ty9phm3iuxdueo3elt5t5fu FOREIGN KEY (achat_journalier_id) REFERENCES public.achat_journalier(id);


--
-- Name: notification fkcxbqr6g1py0j4m9qeq44h1ju6; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkcxbqr6g1py0j4m9qeq44h1ju6 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: compte_courant fkd5soplgcg2l50nc3cafhtvks; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT fkd5soplgcg2l50nc3cafhtvks FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: evaluation_livreur fkdg5g9bwowxsuhm5n2wtw7i0nw; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkdg5g9bwowxsuhm5n2wtw7i0nw FOREIGN KEY (achat_journalier_id) REFERENCES public.achat_journalier(id);


--
-- Name: achat_journalier fkdkrnr7arco3otvydr3dws6yp4; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fkdkrnr7arco3otvydr3dws6yp4 FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseur(id);


--
-- Name: client fkdtcq2s1u9mgkg7gshsop4tvil; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkdtcq2s1u9mgkg7gshsop4tvil FOREIGN KEY (create_by_id) REFERENCES public.app_user(id);


--
-- Name: cloture_journaliere fkeps2thchmjl7nr9c4b5knhk0q; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT fkeps2thchmjl7nr9c4b5knhk0q FOREIGN KEY (cloture_par_id) REFERENCES public.app_user(id);


--
-- Name: epargne_saving fkfam213po3rt9ydtisw93c9x79; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT fkfam213po3rt9ydtisw93c9x79 FOREIGN KEY (created_by_id) REFERENCES public.app_user(id);


--
-- Name: evaluation_livreur fkgbf07m5wwl67doni7ytwcutrc; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkgbf07m5wwl67doni7ytwcutrc FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_compte_courant fkglbudo427kundgohwuql61xtf; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fkglbudo427kundgohwuql61xtf FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: bilan_mensuel fkgw5u6fhmtn1dk91dmlbep7soi; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT fkgw5u6fhmtn1dk91dmlbep7soi FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_saving fkhukhrgkxuqb57jd3tnqyj2b53; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkhukhrgkxuqb57jd3tnqyj2b53 FOREIGN KEY (saving_id) REFERENCES public.epargne_saving(id);


--
-- Name: cloture_journaliere fkkm0otfscswwkn4655faii2ac4; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT fkkm0otfscswwkn4655faii2ac4 FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: evaluation_livreur fkkpnewo8na941btcqy9wmbixrh; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkkpnewo8na941btcqy9wmbixrh FOREIGN KEY (livreur_id) REFERENCES public.livreur(id);


--
-- Name: ligne_achat fklc71754ngp8f0m1mqh8o27duy; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT fklc71754ngp8f0m1mqh8o27duy FOREIGN KEY (produit_id) REFERENCES public.produit(id);


--
-- Name: app_user fkn0x3bn8njtqvcriv1ixw3lagw; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fkn0x3bn8njtqvcriv1ixw3lagw FOREIGN KEY (default_poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: client fknd5od0ba0tna5lvns8y6htgah; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fknd5od0ba0tna5lvns8y6htgah FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_saving fkobjwynn212e9m1t93fcocui9a; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkobjwynn212e9m1t93fcocui9a FOREIGN KEY (effectue_par_id) REFERENCES public.app_user(id);


--
-- Name: employe fkp1wqmjq72mqn8dbfln28rcbl2; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fkp1wqmjq72mqn8dbfln28rcbl2 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: compte_courant fkq47ki93x94wrcv63kddbssny4; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT fkq47ki93x94wrcv63kddbssny4 FOREIGN KEY (created_by_id) REFERENCES public.app_user(id);


--
-- Name: achat_journalier fkrsku8gnxpgttcunot0s18esud; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fkrsku8gnxpgttcunot0s18esud FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_compte_courant fks68ygshjubgchpj8oqe6grdk2; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fks68ygshjubgchpj8oqe6grdk2 FOREIGN KEY (compte_courant_id) REFERENCES public.compte_courant(id);


--
-- Name: employe fksady8dihp5lrk4gdu4978ucgc; Type: FK CONSTRAINT; Schema: public; Owner: fishcam_user
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fksady8dihp5lrk4gdu4978ucgc FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO fishcam_user;


--
-- PostgreSQL database dump complete
--

\unrestrict OAr72SILHXrIdyEh8sq2BttnBPbP8Ai8veEg5Apj4jnv7I9xTEAgKa0hMqGs5CV

