# Nom de l'application
spring.application.name=FishCam

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fishcam_db
spring.datasource.username=fishcam_user
spring.datasource.password=fishcam2025
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.session.jdbc.initialize-schema=always

# Configuration du serveur
server.port=8080

# Format des dates
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=Africa/Douala

# Taille maximale des fichiers (pour futur upload PDF)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuration Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# Logs
logging.level.com.fishcam=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Afficher Authorization button dans Swagger
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true

#resoud le probleme 404
spring.mvc.throw-exception-if-no-handler-found=true


# JWT CONFIGURATION
# Clé secrète JWT (CHANGE-LA EN PRODUCTION !)
jwt.secret=ZmlzaGNhbXN1cGVyc2VjcmV0a2V5MjAyNWNoYW5nZW1laW5wcm9kdWN0assvW9uMTIzNDU2Nzg=
# Durée de validité du token (24 heures en millisecondes)
jwt.expiration=86400000



# Fichier de log (sur le PC local)
#logging.file.name=C:/FishCam/logs/application.log
# Alternative Linux/Mac:
logging.file.name /opt/fishcam/logs/application.log

# Pattern de log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Rotation des logs (nouveau fichier chaque jour)
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

# ═══════════════════════════════════════════════════════════
# RAPPORT JOURNALIER
# ═══════════════════════════════════════════════════════════
# Heure du rapport (format cron)
# Pour TEST: toutes les minutes = 0 * * * * *
# Pour PROD: 19h chaque jour = 0 0 19 * * *
rapport.cron.expression=0 * * * * *

# Activer le rattrapage si PC était éteint
rapport.rattrapage.enabled=true