-- FishCam schema baseline
-- Verified against the production public schema backup dated 2026-08-18.
-- Contains schema objects only: no owners, grants, Supabase internals, or business data.

-- Name: achat_journalier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.achat_journalier (
    id bigint NOT NULL,
    cloture boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_achat date NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    fournisseur_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


--
-- Name: achat_journalier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.achat_journalier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achat_journalier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    active boolean NOT NULL,
    avatar_path character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    role character varying(255) NOT NULL,
    scope character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    default_poissonnerie_id bigint,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY (ARRAY[('SUPER_ADMIN'::character varying)::text, ('PATRON'::character varying)::text, ('CAISSIERE'::character varying)::text, ('ENREGISTREUR'::character varying)::text]))),
    CONSTRAINT app_user_scope_check CHECK (((scope)::text = ANY (ARRAY[('MULTI_POISSONNERIE'::character varying)::text, ('SINGLE_POISSONNERIE'::character varying)::text])))
);


--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    details character varying(1000),
    entity_id bigint,
    entity_name character varying(255) NOT NULL,
    performed_by character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: backup_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backup_record (
    id bigint NOT NULL,
    date_execution timestamp(6) without time zone NOT NULL,
    success boolean NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT backup_record_type_check CHECK (((type)::text = ANY (ARRAY[('LOCAL_DAILY'::character varying)::text, ('CLOUD_WEEKLY'::character varying)::text])))
);


--
-- Name: backup_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.backup_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backup_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bilan_mensuel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bilan_mensuel (
    id bigint NOT NULL,
    annee integer NOT NULL,
    benefice_meilleur_jour numeric(38,2) NOT NULL,
    benefice_net_mois numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    meilleur_jour_benefice date NOT NULL,
    mois integer NOT NULL,
    montant_dettes_mois numeric(38,2) NOT NULL,
    nombre_jours_travailles integer NOT NULL,
    total_achat_mois numeric(38,2) NOT NULL,
    total_depenses_mois numeric(38,2) NOT NULL,
    total_vente_previsible_mois numeric(38,2) NOT NULL,
    total_vente_realisee numeric(38,2) NOT NULL,
    user_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


--
-- Name: bilan_mensuel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bilan_mensuel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bilan_mensuel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    active boolean,
    address character varying(255),
    cni character varying(50),
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth date,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    notes character varying(1000),
    phone character varying(20) NOT NULL,
    quartier character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    create_by_id bigint,
    poissonnerie_id bigint NOT NULL
);


--
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cloture_journaliere; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cloture_journaliere (
    id bigint NOT NULL,
    argent_caisse numeric(38,2) NOT NULL,
    autres_frais numeric(38,2) NOT NULL,
    benefice_net numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    description_autres character varying(500),
    ecart_vente numeric(38,2) NOT NULL,
    fond_de_caisse numeric(38,2) NOT NULL,
    montant_dettes_jour numeric(38,2) NOT NULL,
    montant_rembourse_jour numeric(38,2) NOT NULL,
    nombre_dettes_jour integer NOT NULL,
    ration numeric(38,2) NOT NULL,
    total_achat numeric(38,2) NOT NULL,
    total_depenses numeric(38,2) NOT NULL,
    total_vente_previsible numeric(38,2) NOT NULL,
    transport numeric(38,2) NOT NULL,
    vente_realisee numeric(38,2) NOT NULL,
    cloture_par_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL
);


--
-- Name: cloture_journaliere_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cloture_journaliere ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cloture_journaliere_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compte_courant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.compte_courant (
    id bigint NOT NULL,
    date_ouverture timestamp(6) without time zone NOT NULL,
    limite_credit_max numeric(10,2) NOT NULL,
    solde numeric(10,2) NOT NULL,
    statut character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id bigint,
    CONSTRAINT compte_courant_statut_check CHECK (((statut)::text = ANY (ARRAY[('ACTIF'::character varying)::text, ('SUSPENDU'::character varying)::text, ('BLOQUE'::character varying)::text])))
);


--
-- Name: compte_courant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.compte_courant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compte_courant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employe (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(50) NOT NULL,
    poste character varying(50) NOT NULL,
    prenom character varying(50) NOT NULL,
    salaire numeric(38,2) NOT NULL,
    telephone character varying(20),
    updated_at timestamp(6) without time zone NOT NULL,
    poissonnerie_id bigint NOT NULL,
    user_id bigint
);


--
-- Name: employe_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: epargne_saving; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epargne_saving (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_balance numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id bigint
);


--
-- Name: epargne_saving_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.epargne_saving ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.epargne_saving_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation_livreur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluation_livreur (
    id bigint NOT NULL,
    commentaire character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    date_evaluation date NOT NULL,
    probleme_signale boolean NOT NULL,
    qualite_produit integer NOT NULL,
    respect_poids integer NOT NULL,
    achat_journalier_id bigint NOT NULL,
    livreur_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: evaluation_livreur_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evaluation_livreur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_livreur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fournisseur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fournisseur (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(255) NOT NULL,
    telephone character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    ville character varying(100)
);


--
-- Name: fournisseur_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fournisseur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fournisseur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ligne_achat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ligne_achat (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    montant_carton numeric(38,2) NOT NULL,
    poids_kg numeric(38,2) NOT NULL,
    prix_unitaire_carton numeric(38,2) NOT NULL,
    prix_vente_kilo numeric(38,2) NOT NULL,
    quantite_cartons integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    achat_journalier_id bigint NOT NULL,
    produit_id bigint NOT NULL
);


--
-- Name: ligne_achat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ligne_achat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ligne_achat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livreur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.livreur (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(255) NOT NULL,
    prenom character varying(255) NOT NULL,
    telephone character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    fournisseur_id bigint NOT NULL
);


--
-- Name: livreur_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.livreur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livreur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(2500) NOT NULL,
    read boolean NOT NULL,
    type character varying(255) NOT NULL,
    poissonnerie_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY (ARRAY[('COMPTE_COURANT_ALERTE'::character varying)::text, ('COMPTE_SOLDE'::character varying)::text, ('RAPPORT_JOURNALIER'::character varying)::text, ('INFO'::character varying)::text])))
);


--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poissonnerie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.poissonnerie (
    id bigint NOT NULL,
    active boolean NOT NULL,
    address character varying(225),
    created_at timestamp(6) without time zone NOT NULL,
    fond_de_caisse_defaut numeric(38,2) NOT NULL,
    loyer numeric(38,2) NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20),
    pret_actif boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: poissonnerie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.poissonnerie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.poissonnerie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produit (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    nom character varying(100) NOT NULL,
    poids_par_carton numeric(38,2) NOT NULL,
    unite character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT produit_unite_check CHECK (((unite)::text = 'KG'::text))
);


--
-- Name: produit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.produit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rapport_journalier_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rapport_journalier_record (
    id bigint NOT NULL,
    date_rapport date NOT NULL,
    generated_at timestamp(6) without time zone,
    poissonnerie_id bigint NOT NULL
);


--
-- Name: rapport_journalier_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rapport_journalier_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rapport_journalier_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_compte_courant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_compte_courant (
    id bigint NOT NULL,
    description character varying(500),
    montant numeric(10,2) NOT NULL,
    notes character varying(1000),
    solde_apres numeric(10,2) NOT NULL,
    solde_precedent numeric(10,2) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    compte_courant_id bigint NOT NULL,
    effectue_par_id bigint NOT NULL,
    poissonnerie_id bigint NOT NULL,
    CONSTRAINT transaction_compte_courant_type_check CHECK (((type)::text = ANY (ARRAY[('EMPRUNT'::character varying)::text, ('REMBOURSEMENT'::character varying)::text])))
);


--
-- Name: transaction_compte_courant_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transaction_compte_courant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_compte_courant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_saving; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_saving (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    effectue_par_id bigint,
    saving_id bigint NOT NULL,
    poissonnerie_id bigint,
    CONSTRAINT transaction_saving_type_check CHECK (((type)::text = ANY (ARRAY[('DEPOT'::character varying)::text, ('RETRAIT'::character varying)::text])))
);


--
-- Name: transaction_saving_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transaction_saving ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_saving_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: achat_journalier achat_journalier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT achat_journalier_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: backup_record backup_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_record
    ADD CONSTRAINT backup_record_pkey PRIMARY KEY (id);


--
-- Name: bilan_mensuel bilan_mensuel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT bilan_mensuel_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- Name: cloture_journaliere cloture_journaliere_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT cloture_journaliere_pkey PRIMARY KEY (id);


--
-- Name: compte_courant compte_courant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT compte_courant_pkey PRIMARY KEY (id);


--
-- Name: employe employe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT employe_pkey PRIMARY KEY (id);


--
-- Name: epargne_saving epargne_saving_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT epargne_saving_pkey PRIMARY KEY (id);


--
-- Name: evaluation_livreur evaluation_livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT evaluation_livreur_pkey PRIMARY KEY (id);


--
-- Name: fournisseur fournisseur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fournisseur
    ADD CONSTRAINT fournisseur_pkey PRIMARY KEY (id);


--
-- Name: ligne_achat ligne_achat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT ligne_achat_pkey PRIMARY KEY (id);


--
-- Name: livreur livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livreur
    ADD CONSTRAINT livreur_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: poissonnerie poissonnerie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.poissonnerie
    ADD CONSTRAINT poissonnerie_pkey PRIMARY KEY (id);


--
-- Name: produit produit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT produit_pkey PRIMARY KEY (id);


--
-- Name: rapport_journalier_record rapport_journalier_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT rapport_journalier_record_pkey PRIMARY KEY (id);


--
-- Name: transaction_compte_courant transaction_compte_courant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT transaction_compte_courant_pkey PRIMARY KEY (id);


--
-- Name: transaction_saving transaction_saving_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT transaction_saving_pkey PRIMARY KEY (id);


--
-- Name: evaluation_livreur uk4diy9aab2muyd8m2dfl05yoj9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT uk4diy9aab2muyd8m2dfl05yoj9 UNIQUE (achat_journalier_id);


--
-- Name: bilan_mensuel uk56tjmnqpblm7du851alc14iev; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT uk56tjmnqpblm7du851alc14iev UNIQUE (poissonnerie_id, mois, annee);


--
-- Name: rapport_journalier_record ukay28drjv9uv7usxowuxkbs0t7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT ukay28drjv9uv7usxowuxkbs0t7 UNIQUE (poissonnerie_id, date_rapport);


--
-- Name: compte_courant ukebgufpq02egng08r86sh23x6i; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT ukebgufpq02egng08r86sh23x6i UNIQUE (client_id);


--
-- Name: app_user ukexslcon9jmfy0xhclbtpf26vo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT ukexslcon9jmfy0xhclbtpf26vo UNIQUE (phone);


--
-- Name: cloture_journaliere ukkcy5lrasix4p2qh17hns7aya3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT ukkcy5lrasix4p2qh17hns7aya3 UNIQUE (poissonnerie_id, date);


--
-- Name: produit ukp3flguk26lkj16433geia6xx8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produit
    ADD CONSTRAINT ukp3flguk26lkj16433geia6xx8 UNIQUE (nom);


--
-- Name: epargne_saving ukqsttiq0216iyjcb4h2uw8cwxe; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT ukqsttiq0216iyjcb4h2uw8cwxe UNIQUE (client_id);


--
-- Name: epargne_saving fk208qevee18krn8ec351pmfjrf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT fk208qevee18krn8ec351pmfjrf FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: livreur fk2f6v8ktarlnwewa3en344t8p8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livreur
    ADD CONSTRAINT fk2f6v8ktarlnwewa3en344t8p8 FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseur(id);


--
-- Name: bilan_mensuel fk54v46awfxvqjdvuhh08h2yupd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT fk54v46awfxvqjdvuhh08h2yupd FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: rapport_journalier_record fk5xc3810p5sn8ff872752usjqr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rapport_journalier_record
    ADD CONSTRAINT fk5xc3810p5sn8ff872752usjqr FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_compte_courant fk6slyqg6iil95y6v7mb7iiai3t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fk6slyqg6iil95y6v7mb7iiai3t FOREIGN KEY (effectue_par_id) REFERENCES public.app_user(id);


--
-- Name: achat_journalier fk7va4sbalr59o6qnfr335mbx2g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fk7va4sbalr59o6qnfr335mbx2g FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: notification fkagbo42kulw0dquramrmr4xj5h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkagbo42kulw0dquramrmr4xj5h FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_saving fkao0at72gk95uo4xhnca9iqe1s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkao0at72gk95uo4xhnca9iqe1s FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: ligne_achat fkc4ty9phm3iuxdueo3elt5t5fu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT fkc4ty9phm3iuxdueo3elt5t5fu FOREIGN KEY (achat_journalier_id) REFERENCES public.achat_journalier(id);


--
-- Name: notification fkcxbqr6g1py0j4m9qeq44h1ju6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkcxbqr6g1py0j4m9qeq44h1ju6 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: compte_courant fkd5soplgcg2l50nc3cafhtvks; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT fkd5soplgcg2l50nc3cafhtvks FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: evaluation_livreur fkdg5g9bwowxsuhm5n2wtw7i0nw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkdg5g9bwowxsuhm5n2wtw7i0nw FOREIGN KEY (achat_journalier_id) REFERENCES public.achat_journalier(id);


--
-- Name: achat_journalier fkdkrnr7arco3otvydr3dws6yp4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fkdkrnr7arco3otvydr3dws6yp4 FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseur(id);


--
-- Name: client fkdtcq2s1u9mgkg7gshsop4tvil; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkdtcq2s1u9mgkg7gshsop4tvil FOREIGN KEY (create_by_id) REFERENCES public.app_user(id);


--
-- Name: cloture_journaliere fkeps2thchmjl7nr9c4b5knhk0q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT fkeps2thchmjl7nr9c4b5knhk0q FOREIGN KEY (cloture_par_id) REFERENCES public.app_user(id);


--
-- Name: epargne_saving fkfam213po3rt9ydtisw93c9x79; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epargne_saving
    ADD CONSTRAINT fkfam213po3rt9ydtisw93c9x79 FOREIGN KEY (created_by_id) REFERENCES public.app_user(id);


--
-- Name: evaluation_livreur fkgbf07m5wwl67doni7ytwcutrc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkgbf07m5wwl67doni7ytwcutrc FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_compte_courant fkglbudo427kundgohwuql61xtf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fkglbudo427kundgohwuql61xtf FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: bilan_mensuel fkgw5u6fhmtn1dk91dmlbep7soi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bilan_mensuel
    ADD CONSTRAINT fkgw5u6fhmtn1dk91dmlbep7soi FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_saving fkhukhrgkxuqb57jd3tnqyj2b53; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkhukhrgkxuqb57jd3tnqyj2b53 FOREIGN KEY (saving_id) REFERENCES public.epargne_saving(id);


--
-- Name: cloture_journaliere fkkm0otfscswwkn4655faii2ac4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cloture_journaliere
    ADD CONSTRAINT fkkm0otfscswwkn4655faii2ac4 FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: evaluation_livreur fkkpnewo8na941btcqy9wmbixrh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluation_livreur
    ADD CONSTRAINT fkkpnewo8na941btcqy9wmbixrh FOREIGN KEY (livreur_id) REFERENCES public.livreur(id);


--
-- Name: ligne_achat fklc71754ngp8f0m1mqh8o27duy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ligne_achat
    ADD CONSTRAINT fklc71754ngp8f0m1mqh8o27duy FOREIGN KEY (produit_id) REFERENCES public.produit(id);


--
-- Name: app_user fkn0x3bn8njtqvcriv1ixw3lagw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fkn0x3bn8njtqvcriv1ixw3lagw FOREIGN KEY (default_poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: client fknd5od0ba0tna5lvns8y6htgah; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fknd5od0ba0tna5lvns8y6htgah FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);


--
-- Name: transaction_saving fkobjwynn212e9m1t93fcocui9a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_saving
    ADD CONSTRAINT fkobjwynn212e9m1t93fcocui9a FOREIGN KEY (effectue_par_id) REFERENCES public.app_user(id);


--
-- Name: employe fkp1wqmjq72mqn8dbfln28rcbl2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fkp1wqmjq72mqn8dbfln28rcbl2 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: compte_courant fkq47ki93x94wrcv63kddbssny4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compte_courant
    ADD CONSTRAINT fkq47ki93x94wrcv63kddbssny4 FOREIGN KEY (created_by_id) REFERENCES public.app_user(id);


--
-- Name: achat_journalier fkrsku8gnxpgttcunot0s18esud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achat_journalier
    ADD CONSTRAINT fkrsku8gnxpgttcunot0s18esud FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: transaction_compte_courant fks68ygshjubgchpj8oqe6grdk2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_compte_courant
    ADD CONSTRAINT fks68ygshjubgchpj8oqe6grdk2 FOREIGN KEY (compte_courant_id) REFERENCES public.compte_courant(id);


--
-- Name: employe fksady8dihp5lrk4gdu4978ucgc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fksady8dihp5lrk4gdu4978ucgc FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id);
