-- Suivi du résultat mensuel de gestion : charges, stock et créances constatés.

CREATE TABLE public.charge_gestion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poissonnerie_id bigint,
    categorie character varying(30) NOT NULL,
    libelle character varying(120) NOT NULL,
    montant numeric(15,2) NOT NULL,
    recurrente boolean NOT NULL DEFAULT true,
    date_debut date NOT NULL,
    date_fin date,
    active boolean NOT NULL DEFAULT true,
    created_by_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT charge_gestion_montant_check CHECK (montant >= 0),
    CONSTRAINT charge_gestion_periode_check CHECK (date_fin IS NULL OR date_fin >= date_debut),
    CONSTRAINT charge_gestion_categorie_check CHECK (
        categorie IN (
            'LOYER', 'ELECTRICITE', 'TRANSPORT', 'TAXES', 'SALAIRE',
            'RATION', 'MANUTENTION', 'DIRECTION', 'AUTRE'
        )
    ),
    CONSTRAINT fk_charge_gestion_poissonnerie
        FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id),
    CONSTRAINT fk_charge_gestion_created_by
        FOREIGN KEY (created_by_id) REFERENCES public.app_user(id)
);

CREATE INDEX idx_charge_gestion_active_periode
    ON public.charge_gestion (active, date_debut, date_fin);

CREATE INDEX idx_charge_gestion_poissonnerie
    ON public.charge_gestion (poissonnerie_id);

CREATE TABLE public.releve_situation_mensuelle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poissonnerie_id bigint NOT NULL,
    date_releve date NOT NULL,
    valeur_stock numeric(15,2) NOT NULL,
    total_creances_clients numeric(15,2),
    mode_evaluation character varying(30) NOT NULL,
    note character varying(500),
    saisi_par_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_releve_situation_poissonnerie_date
        UNIQUE (poissonnerie_id, date_releve),
    CONSTRAINT releve_situation_stock_check CHECK (valeur_stock >= 0),
    CONSTRAINT releve_situation_creances_check CHECK (total_creances_clients >= 0),
    CONSTRAINT releve_situation_mode_check CHECK (
        mode_evaluation IN ('COMPTAGE_PHYSIQUE', 'ESTIMATION')
    ),
    CONSTRAINT fk_releve_situation_poissonnerie
        FOREIGN KEY (poissonnerie_id) REFERENCES public.poissonnerie(id),
    CONSTRAINT fk_releve_situation_saisi_par
        FOREIGN KEY (saisi_par_id) REFERENCES public.app_user(id)
);

CREATE INDEX idx_releve_situation_poissonnerie_date
    ON public.releve_situation_mensuelle (poissonnerie_id, date_releve DESC);
